### ISSUE TITLE
Merge functionality of Aoe_Layout module.

### ISSUE THREAD

**Issue by colinmollenhour** [OpenMage/magento-lts#292] opened 2017-06-15 23:06 UTC
As per #282 and #283 this issue is to discuss the inclusion of the functionality added by the Aoe_Layout module. Whereas @LeeSaferite has offered to include it into LTS core and there is no BC issue and it improves the Magento core substantially and is not a "feature" per-se but makes it easier to properly enable/disable features it has my vote for inclusion.

**Comment by Flyingmana** [comment] 2017-06-19 19:36
looks ok for me, but a bit more documentation would be nice

**Comment by niclashoyer** [comment] 2017-07-17 10:31
The repo https://github.com/AOEpeople/Aoe_Layout has no readme file. What does Aoe_Layout add to Magento core?

**Comment by LeeSaferite** [comment] 2017-07-17 14:57
It does have a readme, but it doesn't explain what the module does exactly.

It's meant to enhance several areas of the Layout XML in Magento.

- Unify the element conditionals to be applied to all elements that are processed.
-- Config Conditionals (ifconfig, ifconfig w/!, unlessconfig)
-- ACL Conditionals (acl, acl w/!)
-- Helper Conditionals (ifhelper, ifhelper w/!)
- Adds 'output' attribute handling on reference nodes
-- Allows reference nodes to add/change output attribute value of the parent node
-- Allows the output attribute to be removed by setting it to a blank value
- Adds support for helpers on deeply nested action element parameters
-- Resolution is depth-first
- Adds a few helper methods that work well with the new action parameter helper processing
- Adds a few missing widget methods

**Comment by LeeSaferite** [comment] 2017-07-17 14:58
Also, there are several bits that shouldn't be merged to this repo that are related to generic model handling.

**Comment by LeeSaferite** [comment] 2017-07-17 15:00
I'll generate a PR for this as a change to the core classes instead of as an extension.

**Comment by tomekjordan** [comment] 2017-07-17 16:00
Hi. I'm a merchant.And I never used such things like above (layout module).. and I doubt I will.
why dont you focus on really important things like BUGS? there are many more important things to fix so Magento could be USABLE in production without problems. I raised some issues and nobody helped, but from merchant perspective bugs I described are really important to be fixed. because they make Magento almost unusable for day-to-day operations...

**Comment by Flyingmana** [comment] 2017-07-17 18:33
@tomekjordan thank you for pointing out your worries.
Please know that a major part of this contributions and fixes happen voluntary, and we are thankfully for any of them, even if we have some more needed issues to handle.

If you feel your Issue is to urgent to wait, and is directly impacting your revenue, Iam sure we can find a Developer who has some paid time left in the schedule.

**Comment by sreichel** [comment] 2018-01-11 22:23
@tomekjordan Particually disagree in this ;)

From merchants view ... For me Magento definitly lacks of some layout options that are "required" to customize a shop to your/my needs, like https://github.com/netz98/N98_LayoutHelper (a must - adding css/js in the wight order, remove account link) or  some part of Codnitive_Extifcon (for more flexible layouts - cond. if helpers...) (1)

So, adding things like this makes Magento more USABLE (for me)

> I raised some issues and nobody helped, but from merchant perspective bugs I described are really importantt. because they make Magento almost unusable for day-to-day operations

Definitly agreeded in priority, BUT we all do this here for free and maybe focus on problems we are confrontated with (and have solutions i mind), If you want your issues fixed, please make a PR. If you dont know how to fix, then please add a clearly reproducable step-by-step guide.

> If you feel your Issue is to urgent to wait, and is directly impacting your revenue, Iam sure we can find a Developer who has some paid time left in the schedule.

... :P

> such things like AOE layout module is just nice to have. and nothing more...

Some things should be core features ....

(1) @LeeSaferite can you **PLEASE** add a detailed description to Aoe_Layout?.  Looks far better than `ExtifCon`,but lacks of documentation ... (2)

(2) **PLEASE** :P

**Comment by sreichel** [comment] 2018-01-14 16:20
Found a blog post where it was already mentioned that it should belong to core ... posted 6y ago :)

> @LeeSaferite: I'll generate several PRs for this as changes to the core classes instead of as an extension. Each mini-feature will be it's own PR.

Let's start :) If you need some help ...

**Comment by LeeSaferite** [comment] 2018-01-16 19:51
I'll work on it this weekend

**Comment by luigifab** [comment] 2020-10-08 12:01
Some news :) ?

**Comment by LeeSaferite** [comment] 2020-10-08 17:43
Talk about dropping a ball. I haven't had any time at all to manage this. If someone wants to start I can provided feedback on what should be done.

**Comment by fballiano** [comment] 2022-04-21 12:59
I would suggest to just add the Aoe_Layout module to our "suggested modules" and that's it, it's been 5 years already so...

**Comment by fballiano** [comment] 2022-05-02 12:27
I'm closing this since it seems it's dead. Anybody is welcome to reopen it or better provide a PR.

**Closed by fballiano** 2022-05-02 12:27 UTC
Labels: enhancement, Question
