### ISSUE TITLE
(serious) Issue in sales_flat_order_item after upgrade from 20.0.4 => 20.0.6, sku column suddenly stored using parent sku

### ISSUE THREAD

**Issue by seansan** [OpenMage/magento-lts#1447] opened 2021-02-04 16:13 UTC
(serious) Issue in sales_flat_order_item after upgrade from 20.0.4 => 20.0.6, sku column suddenly stored using parent sku instead of child sku. I would consider this a very urgent breaking change. Proof is added my demonstrating table data that is stored differently then before the upgrade.

## Preconditions (*)
1. Magento 20.0.6

### Steps to reproduce (*)
1. Place new order in backend
2. add child product of configurable

OR 

1. show sold products in order grid (or anywhere coming from sales_flat_order_item)

### Expected result (*)
1. show child SKU
2. and more importantly sku data in sales_flat_order_item is different from how it was stored since ... ever (should store child sku)

### Actual result (*)
1. shows parent SKU
2. sku data in sales_flat_order_item is now parent sku

See images

![image](https://user-images.githubusercontent.com/652395/106921239-1e446780-670c-11eb-90a9-1b267b0a8909.png)

![image](https://user-images.githubusercontent.com/652395/106921261-26040c00-670c-11eb-97ae-b328716a03ae.png)

![image](https://user-images.githubusercontent.com/652395/106921303-2dc3b080-670c-11eb-9dfc-0f5e63ee29b4.png)

**Comment by seansan** [comment] 2021-02-04 16:13
If anyone finds a workaround or hotfix then plz share

**Comment by jouriy** [comment] 2021-02-04 16:19
@seansan, most likely it is caused by #1373, reverting it (#1429) should help.

**Comment by seansan** [comment] 2021-02-04 16:29
This fixes the issue https://github.com/OpenMage/magento-lts/commit/4b172351ee0844d3c9880718da6e181d3571f3f5

**Comment by sicet7** [comment] 2021-02-16 13:29
i accidentally made another issue about this because i scroll past this one sorry :-)

But it would be nice for this to be fixed soon :-)

**Comment by sreichel** [comment] 2021-02-16 23:37
> 
> 
> This fixes the issue [4b17235](https://github.com/OpenMage/magento-lts/commit/4b172351ee0844d3c9880718da6e181d3571f3f5)

Should be fixed with #1429 (1.9.4.11 / 20.0.7) .

**Closed** 2021-02-17 22:49 UTC
Labels: bug, fixed
