### ISSUE TITLE
Invalid attribute name: main_table.store_id

### ISSUE THREAD

**Issue by vovayatsyuk** [OpenMage/magento-lts#939] opened 2020-04-30 06:58 UTC
Looks like there is an incorrect method declared in [Category/Collection](https://github.com/OpenMage/magento-lts/blob/1.9.4.x/app/code/core/Mage/Catalog/Model/Resource/Category/Collection.php#L382-L386):

```
public function addStoreFilter()
{
    $this->addFieldToFilter('main_table.store_id', $this->getStoreId());
    return $this;
}
```

When trying to use it: 

```
echo Mage::getResourceModel('catalog/category_collection')
    ->addStoreFilter()
    ->getSize();
```

The following exception is thrown:

```
Invalid attribute name: main_table.store_id

Trace:
app/code/core/Mage/Eav/Model/Entity/Collection/Abstract.php(1295): Mage::exception('Mage_Eav', 'Invalid attribu...')
app/code/core/Mage/Eav/Model/Entity/Collection/Abstract.php(1388): Mage_Eav_Model_Entity_Collection_Abstract->_addAttributeJoin('main_table.stor...', 'inner')
app/code/core/Mage/Eav/Model/Entity/Collection/Abstract.php(322): Mage_Eav_Model_Entity_Collection_Abstract->_getAttributeConditionSql('main_table.stor...', 1, 'inner')
app/code/core/Mage/Eav/Model/Entity/Collection/Abstract.php(342): Mage_Eav_Model_Entity_Collection_Abstract->addAttributeToFilter('main_table.stor...', 1)
app/code/core/Mage/Catalog/Model/Resource/Category/Collection.php(384): Mage_Eav_Model_Entity_Collection_Abstract->addFieldToFilter('main_table.stor...', 1)
app/code/core/Mage/Cms/controllers/IndexController.php(45): Mage_Catalog_Model_Resource_Category_Collection->addStoreFilter()
app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Cms_IndexController->indexAction()
app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('index')
app/code/core/Mage/Core/Controller/Varien/Front.php(174): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
app/code/core/Mage/Core/Model/App.php(381): Mage_Core_Controller_Varien_Front->dispatch()
app/Mage.php(737): Mage_Core_Model_App->run(Array)
index.php(78): Mage::run('', 'store')
```

[Original Magento](https://github.com/OpenMage/magento-mirror/blob/magento-1.9/app/code/core/Mage/Catalog/Model/Resource/Category/Collection.php) doesn't have this method in a regular category collection (Only in [Flat collection](https://github.com/OpenMage/magento-mirror/blob/magento-1.9/app/code/core/Mage/Catalog/Model/Resource/Category/Flat/Collection.php#L197-L201)).

**Comment by vovayatsyuk** [comment] 2020-04-30 07:24
This method was added to the collection in [PR-884](https://github.com/OpenMage/magento-lts/pull/884).

I'm not sure. Should it work somehow?

**Comment by vovayatsyuk** [comment] 2020-04-30 07:30
JFYI, an error was triggered with the following code: https://github.com/tmhub/easycatalogimg/blob/master/app/code/community/TM/EasyCatalogImg/Block/List.php#L116-L118

```
if (method_exists($collection, 'addStoreFilter')) {
    $collection->addStoreFilter();
}
```

**Comment by colinmollenhour** [comment] 2020-04-30 23:11
I think the problem is likely that the category collection class is different depending on if flat mode is currently enabled. Even if it is enabled it can be temporarily disabled automatically during indexing so you might see this problem come and go. So it probably needs some sort of "if" condition to run different code depending on if flat mode is in use or not.

**Comment by vovayatsyuk** [comment] 2020-05-01 20:30
What about the [method](https://github.com/OpenMage/magento-lts/blob/1.9.4.x/app/code/core/Mage/Catalog/Model/Resource/Category/Collection.php#L382-L386) itself? Is there any way to run it without error?

**Comment by colinmollenhour** [comment] 2020-05-05 21:36
Ahh, I see now.. The method should be fixed in #951. Can you give it a try?

**Comment by vovayatsyuk** [comment] 2020-05-06 06:23
Thank you! It helps.

**Comment by colinmollenhour** [comment] 2020-05-11 15:33
Merged. Thanks for testing!

**Closed** 2020-05-11 15:33 UTC

**Comment by sreichel** [comment] 2025-02-04 21:46
@all-contributors add @vovayatsyuk bug
