### ISSUE TITLE
Type error in Mage_Core_Model_Config::_makeEventsLowerCase

### ISSUE THREAD

**Issue by tmotyl** [OpenMage/magento-lts#1830] opened 2021-09-23 15:45 UTC
https://github.com/macopedia/magento-lts/blob/1.9.4.x/app/code/core/Mage/Core/Model/Config.php#L1714
$event is an object, while addChild expects it to be string.

Probably the solution is to change 
```
$newNode = $events->addChild($newEventName, $event);
```
to
```
$newNode = $events->addChild($newEventName);
```

### Preconditions (*)

1. 
2.

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

**Comment by elidrissidev** [comment] 2022-07-12 11:37
`SimpleXMLElement` defines `__toString` method so it is automatically casted to a string, I also didn't see any `TypeError`s when running with PHP 8.

**Comment by elidrissidev** [comment] 2023-01-13 20:18
Closing since I couldn't reproduce it.

**Closed by elidrissidev** 2023-01-13 20:18 UTC
Labels: PR requested
