### ISSUE TITLE
Warning and Layout

### ISSUE THREAD

**Issue by Marx15** [OpenMage/magento-lts#1444] opened 2021-02-03 11:47 UTC
Hello community

I have a question, I am currently working on 2 test environments.

One has OpenMage LTS 19.4.8 and the baking and admin login page looks almost like Magento 1.
For the others with OpenMage LTS 19.4.10 I have a different layout (a mixture) in the backend and the admin login page has a star space layout. With this version I can't click all tabs in the tab.

Which layout is correct and how can I possibly change something?

With the OpenMage LTS 19.4.10 version, if I want to save something (e.g. General> Design, I get this message:
Your login details cannot be validated.

How can I solve this?

Another mistake
in var / log / system.log I have these notes:
2021-02-03T10: 58: 33 + 00: 00 ERR (3): Warning: SimpleXMLElement :: __ construct (): ^ in /var/www/vhosts/xxxxx.com/xxxxx.com/httpdocs/app/code/ local / Magestore / Magenotification / Model / Magenotification.php on line 96

2021-02-03T10: 58: 33 + 00: 00 ERR (3): Warning: SimpleXMLElement :: __ construct (): Entity: line 7: parser error: Opening and ending tag mismatch: body line 3 and html in / var / www / vhosts / xxxxx.com / xxxxx.com / httpdocs / app / code / local / Magestore / Magenotification / Model / Magenotification.php on line 96

2021-02-03T10: 58: 33 + 00: 00 ERR (3): Warning: SimpleXMLElement :: __ construct (): Entity: line 7: parser error: Premature end of data in tag html line 1 in / var / www / vhosts / xxxxx.com / xxxxx.com / httpdocs / app / code / local / Magestore / Magenotification / Model / Magenotification.php on line 96

Is there a suggestion here?

Many Thanks.

**Comment by dbachmann** [comment] 2021-02-22 15:43
You can use both templates and set the default backend layout in System > Configuration > Advanced > Admin > Admin theme. Try to set the default layout. 
Have a look at PR #1229 

Your second bug is caused by an error in your xml layout files, maybe in the magenotification extension. Have a look at https://digitaldisseny.com/en/blog/72-magento-solve-xml-parsing-issues

**Comment by Marx15** [comment] 2021-02-22 18:51
many thanks for the help.

when I read the lines:
        if (! $ xml) {
            Mage :: log ('XML_ERROR:'. $ String);
        }
in lib / Varien / Simplexml / Config.php

insert, I get the following error messages in system.log:
2021-02-22T18: 37: 10 + 00: 00 DEBUG (7): XML_ERROR: \ <config />
2021-02-22T18: 37: 11 + 00: 00 DEBUG (7): XML_ERROR: \ <theme />
2021-02-22T18: 37: 11 + 00: 00 ERR (3): Warning: SimpleXMLElement :: __ construct (): Entity: line 6: parser error: Opening and ending tag mismatch: hr line 5 and body in / var / www / vhosts / xxxxx.com / xxxxx.com / httpdocs / app / code / local / Magestore / Magenotification / Model / Magenotification.php on line 96
2021-02-22T18: 37: 11 + 00: 00 ERR (3): Warning: SimpleXMLElement :: __ construct (): & lt; / body & gt; in /var/www/vhosts/xxxxx.com/xxxxx.com/httpdocs/app/code/local/Magestore/Magenotification/Model/Magenotification.php on line 96
2021-02-22T18: 37: 11 + 00: 00 ERR (3): Warning: SimpleXMLElement :: __ construct (): ^ in /var/www/vhosts/xxxxx.com/xxxxx.com/httpdocs/app/code/ local / Magestore / Magenotification / Model / Magenotification.php on line 96
2021-02-22T18: 37: 11 + 00: 00 ERR (3): Warning: SimpleXMLElement :: __ construct (): Entity: line 7: parser error: Opening and ending tag mismatch: body line 3 and html in / var / www / vhosts / xxxxx.com / xxxxx.com / httpdocs / app / code / local / Magestore / Magenotification / Model / Magenotification.php on line 96
2021-02-22T18: 37: 11 + 00: 00 ERR (3): Warning: SimpleXMLElement :: __ construct (): Entity: line 7: parser error: Premature end of data in tag html line 1 in / var / www / vhosts / xxxxx.com / xxxxx.com / httpdocs / app / code / local / Magestore / Magenotification / Model / Magenotification.php on line 96
2021-02-22T18: 37: 13 + 00: 00 DEBUG (7): XML_ERROR: \ <\? Xml version = "1.0" \?> \ <jstranslator> \ </jstranslator>
2021-02-22T18: 37: 13 + 00: 00 DEBUG (7): XML_ERROR: \ <\? Xml version = "1.0" \?> \ <config> \ </config>

unfortunately doesn't tell me anything :-(

Is the /httpdocs/app/code/local/Magestore/Magenotification/Model/Magenotification.php still important
active or I can just use / httpdocs / app / code / local / Magestore
to turn off?

**Comment by Marx15** [comment] 2021-02-22 18:56
Here are the mistakes again:

2021-02-22T18: 54: 22 + 00: 00 DEBUG (7): XML_ERROR: \ <config />
2021-02-22T18: 54: 22 + 00: 00 DEBUG (7): XML_ERROR: \ <theme />
2021-02-22T18: 54: 23 + 00: 00 ERR (3): Warning: SimpleXMLElement :: __ construct (): Entity: line 6: parser error: Opening and ending tag mismatch: hr line 5 and body in / var / www / vhosts / xxxxx.com / xxxxx.com / httpdocs / app / code / local / Magestore / Magenotification / Model / Magenotification.php on line 96
2021-02-22T18: 54: 23 + 00: 00 ERR (3): Warning: SimpleXMLElement :: __ construct (): & lt; / body & gt; in /var/www/vhosts/xxxxx.com/xxxxx.com/httpdocs/app/code/local/Magestore/Magenotification/Model/Magenotification.php on line 96
2021-02-22T18: 54: 23 + 00: 00 ERR (3): Warning: SimpleXMLElement :: __ construct (): ^ in /var/www/vhosts/xxxxx.com/xxxxx.com/httpdocs/app/code/ local / Magestore / Magenotification / Model / Magenotification.php on line 96
2021-02-22T18: 54: 23 + 00: 00 ERR (3): Warning: SimpleXMLElement :: __ construct (): Entity: line 7: parser error: Opening and ending tag mismatch: body line 3 and html in / var / www / vhosts / xxxxx.com / xxxxx.com / httpdocs / app / code / local / Magestore / Magenotification / Model / Magenotification.php on line 96
2021-02-22T18: 54: 23 + 00: 00 ERR (3): Warning: SimpleXMLElement :: __ construct (): Entity: line 7: parser error: Premature end of data in tag html line 1 in / var / www / vhosts / xxxxx.com / xxxxx.com / httpdocs / app / code / local / Magestore / Magenotification / Model / Magenotification.php on line 96
2021-02-22T18: 54: 23 + 00: 00 DEBUG (7): XML_ERROR: \ <\? Xml version = "1.0" \?> \ <jstranslator> \ </jstranslator>
2021-02-22T18: 54: 23 + 00: 00 DEBUG (7): XML_ERROR: \ <\? Xml version = "1.0" \?> \ <config> \ </config>

**Comment by sreichel** [comment] 2021-02-22 19:04
> Is the /httpdocs/app/code/local/Magestore/Magenotification/Model/Magenotification.php still important
> active or I can just use / httpdocs / app / code / local / Magestore
> to turn off?

Hi,

`Magestore/Magenotification` is a 3rd-party module. It seams it does not return a valid XML anymore.

**Comment by fballiano** [comment] 2021-03-05 12:01
my suggestion: disable magestore/magenotifican, these kind of modules were always quite useless, now they totally are.

I'd close the issue cause it's not related to openmage.

**Comment by ADDISON74** [comment] 2021-06-21 10:17
We should close open issues like this one. 

Please recommend to all from now one that for asking questions or support to use the new Discussions section.

**Comment by tmotyl** [comment] 2021-06-21 11:17
> Please recommend to all from now one that for asking questions or support to use the new Discussions section.

or Discord channel

**Comment by ADDISON74** [comment] 2021-06-21 12:10
The problem is that we have a very large number of Issues and PR's that can give a negative impression to the project. For example, Bootstrap or Tailwind which are very popular projects on GitHub and which are used by millions of people have surprisingly only a few dozen left open. I don't want to look like a cop but I really want to keep this project alive and fresh as long as I can. Not everyone who migrated to Magento 2 is happy. In the last weeks I tried to contact.

In the last two weeks I have been in contact with several developers who have created extensions and themes for Magento 1 informing them that Magento 1 is not dead and continues as OpenMage. I am probably not the best person for this assignment and one like Colin Mollenhour or Alan Stom have a better pass. It would be great for those who manage OpenMage to think about this option as well until it is too late. Unfortunately, some developers have given up providing extensions for Magento 1, but there are others who have offered them for free or at a reduced price.

**Closed** 2022-05-02 18:31 UTC
