### ISSUE TITLE
BUG SUPEE-11219 – Wrong Field Specified error in 1.9.x - needs a fix

### ISSUE THREAD

**Issue by seansan** [OpenMage/magento-lts#1145] opened 2020-08-12 10:54 UTC
### Preconditions (*)
Install SUPEE-11219 – Wrong Field Specified error in 1.9.x

### Steps to reproduce (*)
Save settings page wih watermark or any other using dynamic, see stack link

### Expected result (*)
Can save config

### Actual result (*)
Cannot save config

### Code

Issue occurs on line 437 in method public function setGroupsSecure($groups) in file /public_html/app/code/core/Mage/Adminhtml/Model/Config/Data.php

![image](https://user-images.githubusercontent.com/652395/90002916-a08b2c00-dc93-11ea-8b22-20951182c38f.png)

One can remove validation on these specific cases for the dynamic fields

Links hinting to a solution, should be fixed

https://magento.stackexchange.com/questions/302944/supee-11219-wrong-field-specified

or remove the warning ;P

https://www.onooks.com/supee-11219-wrong-field-specified/

**Comment by matteorossi-thespacesm** [comment] 2021-01-15 08:53
On a freshly installed OpenMage LTS 19.4.9 test site, when I try and save shipment methods, I get the aforementioned error.
Such error is due to lack of <dynamic_group>1</dynamic_group> configuration in app/code/core/Mage/Shipping/etc/system.xml -> tablerate configuration.

**Comment by seansan** [comment] 2021-01-15 09:26
I dont think the pull must close the issue; it is clar it can occur for many other fields

matteorossi-thespacesm linked a pull request that will close this issue 27 minutes ago

**Comment by matteorossi-thespacesm** [comment] 2021-01-15 10:22
Indeed I've just made a second pull request to fix another issue on catalog module system.xml

**Comment by pisc-software** [comment] 2021-02-04 09:33
We are getting this exception on the following core payment methods:

`core/Mage/Payment/etc/system.xml:
free
cashondelivery
banktransfer
checkmo`

`core/Mage/Authorizenet/etc/system.xml:
authorizenet_directpost`

`core/Mage/Paygate/etc/system.xml:
authorizenet`

...and many more, also in 3rd party extension.
To get around it on these groups adding is required of:
`<dynamic_group>1</dynamic_group>`

We recoded in Mage/Adminhtml/Model/Config/Data.php to simply not populate these fields with data:
`
                /**
                 * FIX: Removing Exception
                if (($groupConfig ? !$groupConfig->dynamic_group : true) && !$this->_isValidField($fieldConfig)) {
                    Mage::throwException(Mage::helper('adminhtml')->__('Wrong field specified.'));
                }
                */
                $groupsSecure[$group]['fields'][$fieldName] = $fieldData;
                if (($groupConfig ? !$groupConfig->dynamic_group : true) && !$this->_isValidField($fieldConfig)) {
                    unset($groupsSecure[$group]['fields'][$fieldName]);
                }
`

**Comment by AGelzer** [comment] 2021-04-21 14:37
See [Cannot save any modification for other selection than Default in Configuration Scope #1417](https://github.com/OpenMage/magento-lts/issues/1417)

Commit that will close this issue:
[Fix regression in configuration scope code. Refs #1417 (#1418)](https://github.com/OpenMage/magento-lts/pull/1418)
Release: v19.4.11

**Comment by Flyingmana** [comment] 2021-05-23 17:26
fixed by #1418

**Closed by Flyingmana** 2021-05-23 17:26 UTC
Labels: bug
