### ISSUE TITLE
Mail queue process (core_email_queue table) stops after OpenMage update 19.4.15 -> 19.4.16

### ISSUE THREAD

**Issue by schmite** [OpenMage/magento-lts#2169] opened 2022-05-30 20:11 UTC
### Preconditions (*)

1. OpenMage LTS 19.4.16 - 4885b20d86bba7aa200007a76620575488e25846
1. Use SMTP send through [Magento-SMTP-Pro-Email-Extension](https://github.com/aschroder/Magento-SMTP-Pro-Email-Extension)
2. PHP 7.3.33

### Steps to reproduce (*)

1. Configure SMTP credentials on Magento-SMTP-Pro-Email-Extension
2. Test emails sending. It works.
3. Update OpenMage version from  19.4.15 to 19.4.16 using `composer update`
4. Test emails send, queue are not processed.

### Expected result (*)

1. When run job `core_email_queue_send_all` we expect tha queue will be processed sending emails.
2. After email send, we expect that `core_email_queue.processed_at` be time stamped.

### Actual result (*)

1. Nothing happens. Emails don't send,  `core_email_queue` table are not updated. No errors on `system.log`, `exception.log`.
2. At `aschroder_smtppro.log` log file occurs the log of dispatching job to send emails queue.

**Comment by fballiano** [comment] 2022-05-30 23:24
do you see the cron jobs running in the cron_schedule table? something like

<img width="1082" alt="Schermata 2022-05-31 alle 00 24 35" src="https://user-images.githubusercontent.com/909743/171067653-8636cab5-0534-4933-87a1-95a4be32a514.png">

**Comment by ADDISON74** [comment] 2022-05-31 08:40
I don't see any PR merged in 1.9.4.16 that could create trouble with emails. You can check the differences between versions here: https://github.com/OpenMage/magento-lts/compare/v19.4.15...v19.4.16.

Did you make an upgrade or an installation from scratch? If it is a new installation is the cron running? As @fballiano suggested before you should take a look into cron_schedule table and check if there are records related to email actions. If there aren't just run in your Magento root the file named cron.sh and check if the table is populated with records.

**Comment by elidrissidev** [comment] 2022-06-02 12:19
@ADDISON74 can you try with mailhog or similar?

**Comment by elidrissidev** [comment] 2022-06-02 14:36
I did a quick test with the following: 
- Latest OM from `1.9.4.x` branch
- Aschroder_SMTPPro v2.0.7
- PHP v8.1.6
- Local SMTP server with MailHog

I created and order, saw the entry in `core_email_queue`, then ran `php -r cron.php` and received it:

<img width="691" alt="Screen Shot 2022-06-02 at 3 29 18 PM" src="https://user-images.githubusercontent.com/67818913/171653454-2032b5e2-b8e6-431a-8c95-833e5c3228a7.png">
<img width="1164" alt="Screen Shot 2022-06-02 at 3 29 33 PM" src="https://user-images.githubusercontent.com/67818913/171653462-3608cd57-a3cb-49bb-b119-53cd4697b9f8.png">

**Comment by ADDISON74** [comment] 2022-06-02 14:51
So we have a first confirmation that the issue cannot be reproduced as reported in the latest version of OM-19. I will come back with my observations too. In case we have at least two confirmations we will close and mark it with the label "bug unconfirmed".

@elidrissidev - Could you please repeat the test this time with OpenMage 20.14? It is the version used by the author of the report.

**Comment by elidrissidev** [comment] 2022-06-02 15:17
@ADDISON74 I don't see anywhere he mentioned using OM 20??

I tried using latest tagged version `v19.4.16` and PHP 7.4.29 same thing emails are sent.

**Comment by ADDISON74** [comment] 2022-06-02 15:25
He did use the OM-19 but it was good to check the OM-20 because it has more extra PR's. 

Let's wait for the author's feedback.

**Comment by elidrissidev** [comment] 2022-06-02 15:39
Works on `20.0` as well.

**Comment by ADDISON74** [comment] 2022-06-03 21:13
I confirm what @elidrissidev said before. OM-20.14 works without any issues with the latest version of this extension Magento-SMTP-Pro-Email-Extension 2.0.7. If it works with OM-20.14 it will work with OM-19 as well.

@schmite - I will close this as the reported bug is not confirmed. We can reopen it at any time if necessary.

**Closed by ADDISON74** 2022-06-03 21:13 UTC
Labels: waiting for feedback, 3rd-party, bug unconfirmed
