### ISSUE TITLE
"Place Order" Button disabled when trying to order virtual products with PayPal-Express

### ISSUE THREAD

**Issue by wilfriedwolf** [OpenMage/magento-lts#1237] opened 2020-09-29 07:36 UTC
### Preconditions (*)
1. Use 1.9.4.x

### Steps to reproduce (*)
1. Use virtual product
2. Try to buy with PayPal Express-Checkout

### Expected result (*)
1. I am able to press the "Place Order" button

### Actual result (*)
1.The button is disabled

### References
Thanks to @sprankhub :
See 
1. https://magento.stackexchange.com/questions/62398/place-order-button-disabled-with-virtual-products-paypal-express-and-terms-and/69815#69815
2. https://github.com/customgento/CustomGento_CoreFixes-m1/pull/7/files
3. https://github.com/customgento/CustomGento_CoreFixes-m1/pull/8

**Comment by wilfriedwolf** [comment] 2020-10-07 07:48
From the - now closed PR:

So now I understand whats going on:

Basically the implementation of the PayPal-Express-Review form is just crap!

Case A: There is a shipping address. Then in 

https://github.com/OpenMage/magento-lts/blob/18739f107de21144a578c8143557f8d2ac6969b3/skin/frontend/base/default/js/checkout/review.js#L63

the Treatment of the submit form is just skipped. That's why it works.

Case B: There is no shipping address. Then in Line 

https://github.com/OpenMage/magento-lts/blob/18739f107de21144a578c8143557f8d2ac6969b3/skin/frontend/base/default/js/checkout/review.js#L77

the event listener is bound to the agreements checkbox disabling the submit button when changing an agreement checkbox.

I guess, what the author of these lines ment to do is to disabling the submit button unless all agreements are checked.

What actually shoud be done is to rewrite this crap in order to check if agreements are checked, preventing submission of the order otherwise just like in the normal checkout.

So as I see it, there is no need to merge the fix from the links, but rather to rewrite the review.js

**Comment by colinmollenhour** [comment] 2020-10-07 09:45
Thanks for your work on this @wilfriedwolf and sorry to hear your rabbit-hole has gotten deeper.. I'm sure the community would appreciate a PR if you find a solid fix for it! Of course minimal BC breakage would be best but we do have two branches now, one for full-BC (19.x) and one for future (20.x).

**Comment by fballiano** [comment] 2022-05-02 12:14
Payment method bugs are very hard to reproduce and work, feel free to reopen it or provide a PR for the fix, but since we've no updates in more that a year, I'm closing this one.

**Closed by fballiano** 2022-05-02 12:14 UTC
Labels: bug
