### ISSUE TITLE
Duplicate Cart Items

### ISSUE THREAD

**Issue by rvelhote** [OpenMage/magento-lts#928] opened 2020-04-16 15:01 UTC
I detected a small bug in our shop that causes duplicate cart items. I'm looking to into this further but I'm not sure if it's something with our shop or Magento.

Here are the steps that I was able to confirm that reproduce.

0. Try to perform this with two clean sessions
1. Create an account (or use an existing account)
2. Log in as a customer with account X
3. Add a product to the cart
4. Switch to a different browser (or a private window)
5. Add the same product as before to the cart
6. Log in as a customer with account X

The contents of the cart will be merged but the same product appears twice.

**Comment by fballiano** [comment] 2022-05-01 20:45
I agree that it is a weird behaviour but it was always like that. The "unlogged" cart gets merged to the "logged" one resulting, sometimes, in some double products, but that's by design.

**Closed by fballiano** 2022-05-01 20:45 UTC
