### ISSUE TITLE
Problem loading image with Easy Configurable Product Matrix PRO plugin (resolved)

### ISSUE THREAD

**Issue by Danieleeffe1** [OpenMage/magento-lts#1566] opened 2021-04-22 11:55 UTC
For those who do not know this is a free Best4Mage plug-in, this plug-in allows the creation of complex configurable products with extreme ease and speed.

I recommend it for those who need to create complex configurable products.

the concept of this plugin is so convenient that it has been copied and inserted into M2.

Unfortunately, however, I encountered a problem in my OpnMage installation

The best4mage software house no longer provides support

The problem I encounter is when uploading images

once the image has been chosen, magento / openmage loading is displayed, but nothing happens, it remains in loop.

If you refresh the page, the system kicks you out of the session and you need to log in again.

I can't figure out if the problem lies with the plugin or with the server.

Do you have any suggestions on how to understand the source of the problem?

Thank you.

for download plug-in:
https://www.best4mage.com/magento-easy-configurable-product-matrix-multiple-attributes.html

**Comment by fballiano** [comment] 2021-04-26 22:05
was the module compatible with the official M1 1.9.4.5? if so, would you be able to provide an updated environment for somebody to test and reproduce the problem?

But most of all, this module seems to have a domain based licensing, it's awful... personally I wouldn't even use it but you should ask best4mage to opensource it (because they're not willing to support it) so that we could fix it for them...

**Comment by Danieleeffe1** [comment] 2021-04-27 04:05
I downloaded it last year magento 1 marketplace before it closed and them
didn't ask for the domain.  I'm not ruling out it's a server problem, but I
don't know how to spot the problem.

Il mar 27 apr 2021, 00:06 Fabrizio Balliano ***@***.***> ha
scritto:

**Comment by fballiano** [comment] 2021-04-27 09:45
again, if you can provide an enviroment where I could get a look, we could try to debug if that's an openmage problem.

anyways my suggestion is to contact them, I wouldn't subscribe to their website just to download that plugin, which for sure has the domain validation which is something I despise when having them in my customer's projects.

**Comment by Danieleeffe1** [comment] 2021-04-28 06:04
ok, I'm not familiar with these procedures.  I have created a specific Cloud server for M2 but multidomain and multi php following various tutorials, I will try to give you the opportunity to verify, what do you need?

**Comment by fballiano** [comment] 2021-04-28 07:48
I tried to download this plugin, checkout took me 15 minutes cause it was never working and now I can't download the plugins for some reason

<img width="1197" alt="Schermata 2021-04-28 alle 08 48 02" src="https://user-images.githubusercontent.com/909743/116366700-7916c800-a7fe-11eb-8b39-118f3b1838c4.png">

if this is the situation, i'm sorry but it doesn't seem reasonable to try to fix this broken thing.

what did the company say?

**Comment by Danieleeffe1** [comment] 2021-04-28 08:12
This Is the originale modulo from market Place magento1
[Ecpm.zip](https://github.com/OpenMage/magento-lts/files/6390162/Ecpm.zip)

**Comment by fballiano** [comment] 2021-04-28 08:17
I've installed it, how can the problem be reproduced?

**Comment by Danieleeffe1** [comment] 2021-04-28 08:29
Enable the module in admin / system / configuration / best4mage / ecpm

create a configurable product so that it has different photos eg tshirt color: white, yellow, red t-shirt.

Go go Tab ecpm

follow the steps until the serial insertion of the product photos

**Comment by fballiano** [comment] 2021-04-28 08:31
app/code/local/Best4Mage/Ecpm/Block/Adminhtml/Catalog/Product/Edit/Tab/Super/Config.php
replace line 613 with

`$url = Mage::getModel('adminhtml/url')->getUrl('*/catalog_product_gallery/upload');`

and it works

<img width="577" alt="Schermata 2021-04-28 alle 09 31 37" src="https://user-images.githubusercontent.com/909743/116372642-89ca3c80-a804-11eb-9810-a1fdbb5ffa80.png">

**Comment by Danieleeffe1** [comment] 2021-04-28 08:47
follow the steps until the serial insertion of the product photos

**Comment by fballiano** [comment] 2021-04-28 08:51
change the line i wrote you in my previous comment and it works

**Comment by Danieleeffe1** [comment] 2021-04-28 14:36
ok, grazie, appena possibili provo. bello collaborare con voi

Il mer 28 apr 2021, 10:51 Fabrizio Balliano ***@***.***> ha
scritto:

**Comment by Danieleeffe1** [comment] 2021-04-28 14:36
Sorry, i use google translation

Il mer 28 apr 2021, 16:35 Daniele Effe ***@***.***> ha scritto:

**Comment by Danieleeffe1** [comment] 2021-04-28 14:36
ok, thanks, I'll try as soon as possible.  nice to cooperate with you

Il mer 28 apr 2021, 16:36 Daniele Effe ***@***.***> ha scritto:

**Comment by fballiano** [comment] 2021-04-28 15:06
oki, when you get it working could you close the issue?

**Comment by Danieleeffe1** [comment] 2021-04-28 15:23
tested, works great.  I hope others enjoy this plugin and your solution

Il mer 28 apr 2021, 17:07 Fabrizio Balliano ***@***.***> ha
scritto:

**Closed** 2021-04-28 15:31 UTC
