### ISSUE TITLE
default template footer should stick to bottom

### ISSUE THREAD

**Issue by f1-outsourcing** [OpenMage/magento-lts#1847] opened 2021-10-02 17:33 UTC
It would be nice / better to modify the default theme so the footer sticks to the bottom (like in magento 2 eg.) It is just annoying seeing this constantly float in the middle of the page. Everyone that extends the default theme will have this.

![footer](https://user-images.githubusercontent.com/13450219/135726638-47fdcbb0-5434-4ca9-8bc5-473a9c9cfee0.png)

**Comment by sreichel** [comment] 2021-10-05 17:30
> 
> 
> This is a feature request not a bug.

Maybe https://github.com/OpenMage/magento-lts/tree/1.9.4.x/.github/ISSUE_TEMPLATE should be revised to better classify problems?

**Comment by ADDISON74** [comment] 2021-10-05 17:54
The Discussions section should be the place for such reports. I moved all my ideas to this section some time ago. We need to differentiate between an issue in the source code and other requests. In this case it can be solved by changing the template but is it useful or is it just an approach to Magento 2? Obviously who wants this footer and can create it for sure would also want it in OpenMage? That is why a discussion is more appropriate at this stage.

I suggest rethinking the templates for a better classify and also to redirect people to debate their ideas in Discussions section.

**Comment by f1-outsourcing** [comment] 2021-10-05 20:07
> 
> 
> This is a feature request not a bug.

Nobody makes websites like this. If it was a feature, it should be revised. Imho magento-lts should out-of-the-box not have this.

**Comment by ADDISON74** [comment] 2021-10-06 13:26
@f1-outsourcing - You can propose a layout and we can discuss from there. You can even create a PR for fixing this issue if you consider it a bug in UI.

**Comment by fballiano** [comment] 2022-05-02 12:30
It's not a bug for sure and since nobody proposed a PR I'll close this issue. Please feel free to create a PR for this and we'll evaluate it, Thank you!

**Closed by fballiano** 2022-05-02 12:30 UTC

**Comment by f1-outsourcing** [comment] 2023-04-29 13:13
I was wondering if this resolved in newer versions, otherwise I will have someone address this. This really looks like crap.


![crap](https://user-images.githubusercontent.com/13450219/235304467-cc0089aa-b5cf-4f97-ad78-c97a0f3f1dbe.png)
