### ISSUE TITLE
CMS Pages Item Count Wrong When Filtering By Store

### ISSUE THREAD

**Issue by sprankhub** [OpenMage/magento-lts#1335] opened 2020-12-10 10:55 UTC
### Preconditions (*)

1. OpenMage LTS 20.0.2
2. Sample data installed

I used https://www.splendid-internet.de/magento-hosting/magento-shop-demo-store-demo-admin-deutsche-version/ to verify the issue.

### Steps to reproduce (*)

1. Log into the backend.
2. Go to CMS > Pages.
3. Verify number of pages (in my case, 19).
![image](https://user-images.githubusercontent.com/930199/101762505-cf000300-3add-11eb-851f-b8fd4f487d92.png)
4. Filter by English store view.

### Expected result (*)

1. Result count should be the same or lower than before applying the filter.

### Actual result (*)

1. Result count is higher than before (in my case, 22) and incorrect. Due to this, a second page is shown, which is completely empty.

![image](https://user-images.githubusercontent.com/930199/101762717-11c1db00-3ade-11eb-8720-c550743d7ca7.png)

![image](https://user-images.githubusercontent.com/930199/101763086-94e33100-3ade-11eb-9ba3-701768941762.png)

I think this can be solved by a similar approach as in `Mage_Catalog_Model_Resource_Product_Collection::_getSelectCountSql`:

https://github.com/OpenMage/magento-lts/blob/9195974dd17e0e207796c6fdd5a02a0c51f7e5c9/app/code/core/Mage/Catalog/Model/Resource/Product/Collection.php#L901-L914

Instead of using `COUNT(*)`, `COUNT(DISTINCT main_table.page_id)` should be used in `Mage_Cms_Model_Resource_Page_Collection::getSelectCountSql`. In my first tests, this solves the issue.

**Comment by colinmollenhour** [comment] 2020-12-11 01:21
I haven't tested this in OpenMage code but here is very general purpose version of `getSelectCountSql()` that uses the same concept as you proposed only generalized to work with any(?) grid and also removes unnecessary joins which can improve performance.

```php
    /**
     * Get SQL for get record count
     *
     * @return Varien_Db_Select
     * @throws Zend_Db_Select_Exception
     */
    public function getSelectCountSql()
    {
        $this->_renderFilters();

        $countSelect = clone $this->getSelect();
        $countSelect->reset(Zend_Db_Select::ORDER);
        $countSelect->reset(Zend_Db_Select::LIMIT_COUNT);
        $countSelect->reset(Zend_Db_Select::LIMIT_OFFSET);
        $countSelect->reset(Zend_Db_Select::COLUMNS);

        // Count doesn't work with group by columns keep the group by
        // http://stackoverflow.com/questions/3485455/using-group-breaks-getselectcountsql-in-magento/4219386#4219386
        if(count($this->getSelect()->getPart(Zend_Db_Select::GROUP)) > 0) {
            $countSelect->reset(Zend_Db_Select::GROUP);
            $group = $this->getSelect()->getPart(Zend_Db_Select::GROUP);
            $countSelect->columns("COUNT(DISTINCT ".implode(", ", $group).")");
        } else {
            $countSelect->columns('COUNT(*)');

            // Simple optimization - remove all joins if there are no where clauses using joined tables and all joins are left joins
            $leftJoins = array_filter($countSelect->getPart(Zend_Db_Select::FROM), function($table) {
                return ($table['joinType'] == Zend_Db_Select::LEFT_JOIN || $table['joinType'] == Zend_Db_Select::FROM);
            });
            if (count($leftJoins) == count($countSelect->getPart(Zend_Db_Select::FROM))) {
                $mainTable = array_filter($leftJoins, function ($table) {
                    return $table['joinType'] == Zend_Db_Select::FROM;
                });
                $mainTable = key($mainTable);
                $mainTable = preg_quote($mainTable, '/');
                $pattern = "/^$mainTable\\.\\w+/";
                $whereUsingJoin = array_filter($countSelect->getPart(Zend_Db_Select::WHERE), function ($clause) use ($pattern) {
                    $clauses = preg_split('/(^|\s+)(AND|OR)\s+/', $clause, -1, PREG_SPLIT_NO_EMPTY);
                    return array_filter($clauses, function ($clause) use ($pattern) {
                        $clause = preg_replace('/[()`\s]+/', '', $clause);
                        return !preg_match($pattern, $clause);
                    });
                });
                if (empty($whereUsingJoin)) {
                    $from = array_slice($leftJoins, 0, 1);
                    $countSelect->setPart(Zend_Db_Select::FROM, $from);
                }
            }
        }

        return $countSelect;
    }
```

**Comment by ADDISON74** [comment] 2022-05-31 22:53
It seems a good improvement provided by @colinmollenhour. Maybe a PR will be a good addition to OM.

**Comment by colinmollenhour** [comment] 2022-06-09 22:43
@ADDISON74  This particular issue seems to be fixed as I couldn't reproduce it but I still opened a PR with the code from my comment (#2210)

**Comment by colinmollenhour** [comment] 2022-06-09 22:45
Closing since I believe this must have already been fixed elsewhere - I could not reproduce the issue.

**Closed by colinmollenhour** 2022-06-09 22:45 UTC
Labels: waiting for feedback, bug confirmed, PR requested
