### ISSUE TITLE
Replace deprecated `strftime` and `gmstrftime` PHP functions

### ISSUE THREAD

**Issue by elidrissidev** [OpenMage/magento-lts#2030] opened 2022-03-02 10:43 UTC
The PHP functions `strftime` and `gmstrftime` were deprecated starting from PHP 8.1 and will be removed in the next major version, we should consider replacing them with alternatives without changing the behavior.

Ref: https://php.watch/versions/8.1/strftime-gmstrftime-deprecated

**Comment by kiatng** [comment] 2022-03-03 01:03
Duplicate of issue #1812 .

**Comment by elidrissidev** [comment] 2022-03-03 08:45
@kiatng Sorry, I didn't notice that PR. Although I do prefer small incremental fixes that are easier to review and merge.

**Comment by kiatng** [comment] 2022-09-27 12:26
Issue #1812 was closed without resolution.

**Closed** 2023-01-16 12:34 UTC
Labels: good first issue, PHP 8.1
