### ISSUE TITLE
category product list swatches always appear in_stock

### ISSUE THREAD

**Issue by ioweb-gr** [OpenMage/magento-lts#3527] opened 2023-09-19 07:02 UTC
### Preconditions (*)

1. OpenMage 20.1.1

### Steps to reproduce (*)

I'm not sure how to replicate this, in our installation we had swatches enabled for configurable products by size and upgraded to the newer version only to see that all swatches even for not-saleable products would show up in category display page, but when the user would click on any product, in the product display page he would see only the saleable products instead. 

It turns out that the stock item is not properly loaded giving me a null value normally when used like this 

` $isInStock = $childProduct->getStockItem()->getIsInStock();`

By switching to load the stock item properly it works perfectly fine

e.g.

```
Index: app/code/core/Mage/ConfigurableSwatches/Helper/Mediafallback.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/app/code/core/Mage/ConfigurableSwatches/Helper/Mediafallback.php b/app/code/core/Mage/ConfigurableSwatches/Helper/Mediafallback.php
--- a/app/code/core/Mage/ConfigurableSwatches/Helper/Mediafallback.php	
+++ b/app/code/core/Mage/ConfigurableSwatches/Helper/Mediafallback.php	(date 1695106866756)
@@ -100,7 +100,8 @@
 
                 foreach ($parentProduct->getChildrenProducts() as $childProduct) {
                     // product has no value for attribute or not available, we can't process it
-                    $isInStock = $childProduct->getStockItem()->getIsInStock();
+                    $stockItem = Mage::getModel('cataloginventory/stock_item')->loadByProduct($childProduct);
+                    $isInStock = $stockItem->getIsInStock();
                     if (!$childProduct->hasData($attribute->getAttributeCode())
                         || (!$isInStock && !Mage::helper('cataloginventory')->isShowOutOfStock())
                     ) {
```

### Expected result (*)

1. Only salable products appear

### Actual result (*)

1. All swatches appear even for the not-available products 

# CDP
![image](https://github.com/OpenMage/magento-lts/assets/20220341/6cc01196-07a2-424a-bde7-10d7bf7d9138)

# PDP
![image](https://github.com/OpenMage/magento-lts/assets/20220341/7322284f-cb0b-4bde-b6c8-9c5b01af09ea)

**Comment by elidrissidev** [comment] 2023-09-20 11:33
This seems like a duplicate of #1694, can you confirm or is it a new bug in this version?

**Comment by ioweb-gr** [comment] 2023-09-20 12:48
My case is only for the list page , not the product page so I think it's related but not the same

**Closed** 2024-09-22 21:19 UTC
Labels: needs investigation
