### ISSUE TITLE
Filter "all" in admin panel grid is not getting used

### ISSUE THREAD

**Issue by acjandupont** [OpenMage/magento-lts#2275] opened 2022-07-05 15:32 UTC
### Preconditions (*)

1. v19.4.16

### Steps to reproduce (*)

1. Go to a **product** (Catalog -> manage catalog -> select any product)
2. Open the tab "Related products", "Up-sells" or "Cross-sells"
3. If no products are selected there select a few products using the checkboxes in front and save the product
4. return to step 2 and filter on "all"

### Expected result (*)

Using "all" it should show all products in the grid, the ones checked as well as the ones unchecked.

### Actual result (*)

Using "all" it refreshes the grid with option "yes" selected. The "all" filter is not taken into account. When you look at the requests done you can see that for "yes" and "no" options is passes a "filter" parameter containing a base64 encoded value with "in_products=1" and "in_products=0". For option "all" it doesn't pass the filter param. The controllers should fall back to returning both but instead fall back to the "yes" option rendering the option "all" broken

**Comment by luigifab** [comment] 2022-07-06 12:38
You are right, when no products are selected, when "All" is selected, after press "Search" button, "Yes" is selected.

**Comment by fballiano** [comment] 2022-07-07 08:54
did somebody tried agains current 1.9.4.x branch?

**Comment by ADDISON74** [comment] 2022-07-07 10:03
Although I offered a reply a day ago that could be a solution the author of the post did not come up with feedback. 

I will do a test today cloning the repo with all merged PR's up to date. With git installed is easy to switch between branches, the only thing to do is cleaning up the cache before using each version.

**Comment by ADDISON74** [comment] 2022-07-10 13:50
I tested it according to the instructions with the latest version of the cloned Magento 1.9.4.16.  I confirm that it cannot be reproduced. As previously stated it was resolved through PR #2177. 

As the author did not provide any feedback and the issue is not confirmed I will close the report.

**Closed by ADDISON74** 2022-07-10 13:50 UTC
Labels: needs investigation
