### ISSUE TITLE
TBD: setEmailSent on Invoice

### ISSUE THREAD

**Issue by infabo** [OpenMage/magento-lts#267] opened 2017-05-22 09:00 UTC
This one should be discussed if it is a bug or an intended behaviour.

When you create a new invoice, you have this checkbox:

![grafik](https://cloud.githubusercontent.com/assets/3999104/26299839/8e75bd6c-3edc-11e7-897f-f2a2a7e4d5ef.png)

If not checked and no "invoice-copy-to-recepiants" defined (configuration / sales emails) -> all working fine and you get the expected status-message:

![grafik](https://cloud.githubusercontent.com/assets/3999104/26300027/35cdab6a-3edd-11e7-92d7-fb42c2c5c4cb.png)

Once you have entered some "invoice-copy-to-recepiants":

![grafik](https://cloud.githubusercontent.com/assets/3999104/26300095/6ca1f326-3edd-11e7-9cf9-9b1496076601.png)

In both cases no email is sent to the customer customer -> expected behaviour.

Just because an CC email is sent, the "email_sent" flag is set to true.

Received feedback from several merchants, saying this is confusing.

source:

https://github.com/OpenMage/magento-lts/blob/1.9.3.x/app/code/core/Mage/Sales/Model/Order/Invoice.php#L847

**Comment by seansan** [comment] 2017-05-22 09:15
I am a merchant ;) And would agree: all messages on order level implicitly
implie *the customer*

**Comment by LeeSaferite** [comment] 2017-05-22 14:48
I'd personally say this is 100% a bug. The implicit "sent to customer" in that message is something I've always taken for granted.

You can see that Invoice and Creditmemo are both exhibiting this behaviour.
[Invoice](https://github.com/OpenMage/magento-lts/blob/1.9.3.x/app/code/core/Mage/Sales/Model/Order/Invoice.php#L847)
[Creditmemo](https://github.com/OpenMage/magento-lts/blob/1.9.3.x/app/code/core/Mage/Sales/Model/Order/Creditmemo.php#L794)

It seems like Shipments are not just due to someone forgetting to add that code in the sendEmail method. The controllers that generate the calls to sendEmail are *also* setting the flag, but for Invoice and Creditmemo that are being overridden.

I would say a few things should be fixed. First, refactor Invoice, Creditmemo, and Shipment sendEmail to use the email queue. This will help address the weirdness in the code caused by trying to prevent an email send failure from triggering a transaction rollback. Second, remove the flag setting in the controllers and move the sendEmail call back inside the transaction scope. Third, ensure that the sendEmail method is, in all cases, setting the sent_email value to the same as the $notifyCustomer flag.

**Comment by tomekjordan** [comment] 2017-05-22 14:52
related to #245 I think

**Comment by ADDISON74** [comment] 2022-06-01 13:54
I am trying to reproduce this issue.

**FIRST SCENARIO**
- I placed an order in Frontend.
- In Backend I went to Sales -> Orders and viewed the order I placed.
- I pressed [Invoice] button then in the New Invoice for Order #XXXXX I pressed [Submit Invoice] button.
- I went back in "Order View" page and I pressed on the left side "Invoices" tab. In the grid I accessed the only created invoice. In the new page the header says "Invoice #103000004 | Paid | Jun 1, 2022 6:37:30 AM (the invoice email is not sent)".
- I pressed [Send Email] button and in the reloaded page the header says "Invoice #103000004 | Paid | Jun 1, 2022 6:37:30 AM (the invoice email was sent)". In customer's inbox I got the email with Invoice #103000004 subject.

**SECOND SCENARIO**
- I placed a new order in Frontend.
- In Backend I went to Sales -> Orders and viewed the order I placed.
- I pressed [Invoice] button then in the New Invoice for Order #XXXXX I checked "Email Copy of Invoice" then I pressed [Submit Invoice] button.
- I am now in "Order View" page and I pressed on the left side "Invoices" tab. In the grid I accessed the only listed invoice. In the new page the header says "Invoice #103000005 | Paid | Jun 1, 2022 6:45:21 AM (the invoice email was sent)"
- Indeed in customer's inbox there is an email with Invoice #103000005 subject.
- I pressed [Send Email] button and I got the same email in customer's inbox.

As can be seen in both scenarios the behavior is as expected. There are no issues related to the sending of an invoice to the customer. If I did not reproduce this issue correctly I am waiting to be told what to do next. If I don't get any reply in 2 weeks I will close the issue.

**Comment by justinbeaty** [comment] 2022-06-01 15:54
@ADDISON74 It would seem the issue stems from having this field set in the backend:

![image](https://user-images.githubusercontent.com/51970393/171447247-d52b8d00-4255-421f-bfac-155eadc868dd.png)

Then, creating an invoice and not checking the "Email Copy of Invoice" box. I have not tried to reproduce it though.

**Comment by elidrissidev** [comment] 2022-10-01 23:45
This issue was already fixed in #297

**Closed** 2022-10-01 23:45 UTC
Labels: waiting for feedback, needs investigation
