### ISSUE TITLE
Twice tax in Grand Total

### ISSUE THREAD

**Issue by idziakjakub** [OpenMage/magento-lts#80] opened 2016-04-14 10:23 UTC
After upgrade Magento from 1.9.2.2 to 1.9.2.4 I have doubled tax amount in Quote.

I have found solution for this issue: 
http://stackoverflow.com/questions/17590364/magento-applying-tax-vat-twice/35870460#35870460

The problem occurs when you have additional totals in project.
The problem can be solved by adding correct dependencies on tax subtotal, so Magento keep the correct order.

**Comment by tmotyl** [comment] 2016-05-09 09:55
+1

**Comment by tmotyl** [comment] 2016-10-11 10:56
fixed in https://github.com/OpenMage/magento-lts/commit/b9726b9997e2bece26d37d91c92f32fbb18aebb4

**Closed by tmotyl** 2016-10-11 10:56 UTC

**Comment by hannes011** [comment] 2020-07-09 11:14
This is a major change which is causing troubles for the calculation of shipping rate! Is "shipping" really needed as prerequisite for subtotal?
A: shipping is not included within subtotal
B: some shipping methods calculate there rate based on subtotal

This change led to strange behavior: once the totals are already calculated and stored/cached then the subtotal doesn't include tax anymore (as expected) BUT when totals will be collected first time the "shipping" total is executed before "tax_subtotal", so the subtotal still contains tax, which leads to inconsistency...
![image](https://user-images.githubusercontent.com/12843419/87032376-d21c5d80-c1e4-11ea-81f8-af7ee1fa3656.png)

FYI @tmotyl @sreichel @idziakjakub

**Comment by Schrank** [comment] 2020-07-09 11:34
I saw it and maybe this is important for this: https://blog.fabian-blechschmidt.de/mage_weee-and-why-it-is-important-for-tax-calculation/
(didn't dig into it)

**Comment by Schrank** [comment] 2020-07-09 11:35
Maybe you want to include https://github.com/ikonoshirt/TopologicalSearch into OpenMage, happy if you do! <3

**Comment by hannes011** [comment] 2020-07-09 11:42
Simple fix would be just this I guess:
```diff --git a/app/code/core/Mage/Tax/etc/config.xml b/app/code/core/Mage/Tax/etc/config.xml
--- a/app/code/core/Mage/Tax/etc/config.xml
+++ b/app/code/core/Mage/Tax/etc/config.xml
@@ -162,7 +162,7 @@
                 <totals>
                     <tax_subtotal>
                         <class>tax/sales_total_quote_subtotal</class>
-                        <after>subtotal,nominal,shipping,freeshipping</after>
+                        <after>subtotal,nominal,freeshipping</after>
                         <before>tax,discount</before>
                     </tax_subtotal>
                     <tax_shipping>
```

**Comment by henrykbrzoska** [comment] 2020-07-10 05:33
Isn't it dependent on the principles of calculating tax(country of taxation)?

**Comment by lemundo-team** [comment] 2020-07-13 14:34
Hi @henrykbrzoska 
it's actually only on the base principle that subtotal does not contain shipping but shipping may be based on subtotal

**Comment by lemundo-team** [comment] 2020-07-13 14:37
@tmotyl @sreichel @idziakjakub we have provided a pull request to solve this issue but it needs to be reviewed: #1104

**Comment by doejoe13** [comment] 2020-07-28 07:23
Hello, got exactly same issue after upgrade from 1.7. Using owebia/magento1-module-advanced-shipping for shipping, rates calculated on weight. Fix suggested by @hannes011 is not working for me. Neither solution from https://community.magento.com/t5/Magento-1-x-Technical-Issues/After-upgrading-from-1-9-3-7-to-1-9-3-9-issue-regarding-shipping/m-p/112864#M9109

**Comment by doejoe13** [comment] 2020-07-29 06:16
My issue was caused by connect20/flywebdesign_paypalfee extension. After removed it, everything is OK.
