### ISSUE TITLE
Apply Patch for Shopping cart price rules - Condition subselection issue

### ISSUE THREAD

**Issue by diglin** [OpenMage/magento-lts#110] opened 2016-10-10 12:17 UTC
This patch fix issue with Shopping Cart Rule as mentioned here: http://magento.stackexchange.com/questions/46428/magento-1-9-1-shopping-cart-price-rules-condition-subselection-issue

It's old but still actual
https://gist.github.com/piotrekkaminski/54529dadb0bc01a62a2d

**Comment by sreichel** [comment] 2017-03-02 15:33
Duplicate of #56 ???

**Comment by diglin** [comment] 2017-03-02 16:14
possible but the solution is provided

**Comment by sreichel** [comment] 2017-03-02 16:35
@diglin it seems to be fixed in 1.9.3.0 ... can you test it, too?

**Comment by diglin** [comment] 2017-03-06 09:47
@sreichel sorry, unfortunately I'm not anymore on this topic, it was few months ago I send the feedback.

**Closed** 2017-04-01 23:58 UTC
Labels: confirmation required, duplicate
