### ISSUE TITLE
HEADERS ALREADY SENT

### ISSUE THREAD

**Issue by Marx15** [OpenMage/magento-lts#1696] opened 2021-06-21 09:31 UTC
Hi

I have a question about errors that I currently have:

2021-06-17T07:34:18+00:00 DEBUG (7): HEADERS ALREADY SENT: <pre>[0] /...../app/code/core/Mage/Core/Controller/Response/Http.php:52
[1] /...../lib/Zend/Controller/Response/Abstract.php:768
[2] /...../app/code/core/Mage/Core/Controller/Response/Http.php:87
[3] /...../app/code/core/Mage/Core/Controller/Varien/Front.php:204
[4] /...../app/code/core/Mage/Core/Model/App.php:381
[5] /...../app/Mage.php:752
[6] /...../index.php:72
</pre>

These errors appear on every page that is visited. The funny thing is that there were no such errors in a testshop.

maybe someone can help me or has a solution?

many thanks

**Comment by ADDISON74** [comment] 2021-06-21 09:37
Is this an issue in the latest OpenMage version? Please provide all steps you have done to reproduce it staring with your environment.

I just installed OM 20.0.10 today for testing an extension and by enabling all logs and I did not get any errors.

**Comment by Marx15** [comment] 2021-06-21 09:40
thanks in advance

I have OpenMage LTS 19.4.13
Installed.
Every time you visit the Fronted, the errors appear as indicated.

**Comment by ADDISON74** [comment] 2021-06-21 10:14
Is it a Magento only or a Magento with customizations like themes, extensions, changes in code, etc.? 

Install OM 20.0.10 only create a product and repeat all steps to reproduce the errors. I am sorry to say but in Magento 1.9.4.13 I was not able to reproduce your log errors.

**Comment by Marx15** [comment] 2021-06-21 10:22
yes I am surprised too. As I said, I don't have these errors in my test shop.
it's magento and on openmage.
What I may have noticed is that these errors showed up after the online (live).

**Comment by ADDISON74** [comment] 2021-06-21 12:12
I guess in production it is not the same server. Check you server configuration especially for PHP with its modules.

I am sorry I cannot help you because I was not able to reproduce this issue with Magento and OpenMage. You should ask for help on Stackexchange too.

**Comment by kiatng** [comment] 2021-06-22 00:02
Check issue #246 on some tips to debug and possible related issue #1129.

**Comment by fballiano** [comment] 2022-05-02 18:17
closing since no inpute since almost one year

**Closed by fballiano** 2022-05-02 18:17 UTC
