### ISSUE TITLE
new admin theme menus are harder to navigate when using a sensitive mouse

### ISSUE THREAD

**Issue by ioweb-gr** [OpenMage/magento-lts#1233] opened 2020-09-26 08:05 UTC
### Preconditions (*)
1. OpenMage 20.0.3

### Steps to reproduce (*)
1. Use a mouse with sensitivity controls and increase it to a high speed. 
2. Try to navigate the menus

### Expected result (*)
The menus are easy to navigate for the user without accidentally popping out menus 

### Actual result (*)
When actually navigating dropdown menus the 3rd level menu items popup is very close to the middle of the 2nd level items. 
Then when the mouse is moving fast enough it's hard to maintain a straight line. I think the popup should be attached on the right side near the arrow symbol while now it's like this. 

![image](https://user-images.githubusercontent.com/20220341/94335981-26ff9100-ffe8-11ea-9305-6ecfb52b76a6.png)

**Comment by fballiano** [comment] 2022-05-02 12:11
Not sure if it was fixed in the meanwhile but I can't reproduce the error, since there's quite some space it actually seem pretty easy to navigate to the submenus

**Closed by fballiano** 2022-05-02 12:11 UTC
Labels: bug
