### ISSUE TITLE
sales_order_create_sidebar_wishlist breaks if wishlist module is disabled

### ISSUE THREAD

**Issue by Flyingmana** [OpenMage/magento-lts#268] opened 2017-05-24 16:15 UTC

**Comment by sreichel** [comment] 2017-05-28 16:29
Again ... please add some code to reproduce ;)

**Comment by Flyingmana** [comment] 2017-05-28 19:00
I will, just wanted to fast note this issue to not forget about it

**Comment by fballiano** [comment] 2022-05-01 19:09
I'll close this issue just because I've created the PR and the description is much better on the PR than here.

**Closed by fballiano** 2022-05-01 19:09 UTC
Labels: waiting for feedback
