### ISSUE TITLE
1931 Order comments - notification disabled but BCC gets email

### ISSUE THREAD

**Issue by tomekjordan** [OpenMage/magento-lts#245] opened 2017-03-15 09:32 UTC
HI. I just found that If I add order comment for staff only. Without NOTIFY Customer checkbox, if Sales Emails > Order Comments are Enabled globally, and option BCC is filled with email. BCC gets email. Customer is not getting emails if NOTIFY is not checked - its OK, but no matter its checked or not, BCC gets  it. I think it can be fixed.
Separate mail works differently. Case is for BCC

Thanks

**Comment by sreichel** [comment] 2017-03-22 20:21
> but no matter its checked or not, BCC gets it.
Sound as working as intented. If you dont want wo get emails leave BCC blank?

**Comment by tomekjordan** [comment] 2017-03-22 20:34
HI. no, its not working as intented.
If I like to disable emails for order comments - it should not be sent even to BCC.
There are automatic order notifications, and manuals. So if I remove BCC from this field I will be BCCed for manual comments as admin, while I don/t want automatic one to be sent to customers each time. And I prefer to send it manually from order detail page. I hope you know what I mean :)

**Comment by drobinson** [comment] 2017-04-01 21:20
I think what @sreichel is saying is that you are unchecking the *customer* checkbox, not a *configured bcc* checkbox.  In that case, this seems more like a feature not working the way you'd like, instead of a bug per se.  Thoughts?

**Comment by tomekjordan** [comment] 2017-04-21 17:29
Nope, because general settings are not working that way, so if I don't send message to customer - why BCC admin should get it? the message is never sent to customer - so admin or any other bcc should also not be generated....

**Comment by LeeSaferite** [comment] 2017-05-22 14:58
So, since I'm here from #267 I'd like to put in my thoughts. The BCC emails are always sent for every other email in the system if they are configured, regardless of the send to customer flag. This is how everything else works currently. So, I'd disinclined to think this is buggy behaviour. 

That being said, I'd be open to discussing the merits of a new config flag to control this behaviour. My only concern would be that it's not fixing a bug, but adding a feature and I think that strays outside of what LTS was meant to cover. Personally I'm ok with that, but I'm not a BDFL or anything so fun.

**Comment by tomekjordan** [comment] 2017-05-22 15:00
I dont think BCC email should be sent without main email, and thats behavior I described regarding adding comments without notify user...

**Comment by tomekjordan** [comment] 2017-07-07 21:03
Another strange behavior: Order canceled by payment gate, showing that user is not notified, but user is notified - I checked it on smtp log. http://prntscr.com/fsyix9
Those all problems comes from BCC, Separate copy bug I think - as I mentioned above, there are some kind  strange bugs in it - if configuration has Emails OFF, but field BCC,separate email is filled with email - it send emails instead of just shut them off for both (customers and admin's BCC/separate emails)

thanks for tweaking it finally

**Comment by tmotyl** [comment] 2017-07-17 16:56
For me to be able to move forward with this issue/request I need more context in terms of what is the current magento behaviour in differen places. This way we can validate what is the "usual" and what is an exception/bug. Without a full picture I'm afraid that fixing one place will do more harm than good.

@tomekjordan if you could provide a summary of how Magento behaves in terms of sending BCC emails and different checkboxes being set, that would be helpful for me to understand the bug picture, and later to test the proposed patch.

**Comment by tomekjordan** [comment] 2017-07-17 17:07
@tmotyl I've sent you linkedin msg
I can make some screenshots for this. there is some stupid Magento behavior that send BCC message if the BCC field is filled but it sends to those BCCs even this type of email is DISABLED in general config. It affects order emails vs order comments, invoice emails (invoice comments - but this is rare used). will explain deeply later with screenshots. thx

**Comment by fballiano** [comment] 2022-05-01 18:48
I'm closing this issue since it's 5years old, the first point seems to be "by design", altough questionable. For the second part of this issue (the payment capture) please open a separate issue (it because very complicated for us to manage issues that fork through different topics) possibly with a PR.

**Closed by fballiano** 2022-05-01 18:48 UTC
