### ISSUE TITLE
Twice URL escaped when changing the sorting

### ISSUE THREAD

**Issue by abdel-aouby** [OpenMage/magento-lts#1662] opened 2021-05-28 16:07 UTC
### Preconditions (*)

1. Tested on live sandbox : https://www.softaculous.com/demos/Magento_1.9
2. Confirmed in last openMage  magento-lts version

### Steps to reproduce (*)

1. Search some string with none latine letter (e.g: Šaty  OR zesilovač)
![image](https://user-images.githubusercontent.com/56534840/120011024-1facdf00-bfde-11eb-9088-0d97e5fadb38.png)

2. Change the sorting
![image](https://user-images.githubusercontent.com/56534840/120011181-4f5be700-bfde-11eb-9192-5aa8c9c6d2f0.png)

3. the result is broken
![image](https://user-images.githubusercontent.com/56534840/120011299-6bf81f00-bfde-11eb-9b1e-ea5008020ade.png)

### Expected result (*)

1. ![image](https://user-images.githubusercontent.com/56534840/120011463-9944cd00-bfde-11eb-9cd8-ecccbb17159e.png)

### Actual result (*)

1. ![image](https://user-images.githubusercontent.com/56534840/120011669-dad57800-bfde-11eb-8256-1e123218b7ac.png)

Possibly the problem is happening here: js/varien/js.js:31

**Comment by ADDISON74** [comment] 2021-05-28 21:10
**I confirm this bug related to special characters.** 

Let's take as example **oléorésine** which is a French word and observe the URL and the search box contents.

By filling up the word in the search box then clicking on [Search] button the results are:
- **Search box**: oléorésine
- **URL**: /catalogsearch/result/?q=oléorésine

Now changing the **Sort By** from "Relevance" to any values like "Price" or "Name" the results are:
- **Search box**: ol%C3%A9or%C3%A9sine
- **URL**: /catalogsearch/result/index/?dir=asc&order=name&q=ol%25C3%25A9or%25C3%25A9sine

By using the sort feature é character becomes %25C3%25A9. Obviously the search result is that no products were found.

Let's take a look at the source code of the page after the initial search. Here is the select tag responsible for Sort action:

```
<select onchange="setLocation(this.value)" title="Sort By">
  <option value="https://www.mydomain.tld/catalogsearch/result/index/?dir=asc&amp;order=relevance&amp;q=ol%C3%A9or%C3%A9sine" selected="selected">Relevance</option>
  <option value="https://www.mydomain.tld/catalogsearch/result/index/?dir=asc&amp;order=name&amp;q=ol%C3%A9or%C3%A9sine">Name</option>
  <option value="https://www.mydomain.tld/catalogsearch/result/index/?dir=asc&amp;order=price&amp;q=ol%C3%A9or%C3%A9sine">Price</option>
</select>
```
As you can see these links are built incorrectly.

**Comment by jfksk** [comment] 2021-05-29 23:23
I also can confirm this _double encoding problem_ in js/varien/js.js (setLocation). Is there any functional or security implication with the following change?


Replace
```
function setLocation(url){
    window.location.href = encodeURI(url);
}
```

with 

```
function setLocation(url){
    window.location.href = encodeURI(decodeURI(url));
}
```

It seems to work for German and basic cases but I'm not sure about other languages and special cases and security implications.

**Comment by ADDISON74** [comment] 2021-05-30 07:44
I confirm @jfksk solution is solving this issue for the French word oléorésine. In browser address the URL is not encoded but URL's for Sort By and Pagination are. By changing the values in Sort By list it works as expected , also the sort directions and paginations.

I don't know what security implications could have this combination encode(decode) which seems to cancel each other out. I will try finding some articles on Internet. Here is one https://www.geeksforgeeks.org/javascript-encodeuri-decodeuri-and-its-components-functions/

**Comment by midlan** [comment] 2021-09-06 12:56
Seems that the escape inside `setLocation` was added as reaction to some forgot escape in some template. Would be hard to find it.

**Comment by elidrissidev** [comment] 2022-10-02 09:58
I was looking at this issue and I did find some instances where an unescaped URL is passed to `setLocation` (hence where it's being encoded inside). Now the question is should we remove `decodeURI` and make sure that all URLs passed to `setLocation` are escaped, but that might be a problem for 3rd party extensions

**Comment by sreichel** [comment] 2023-01-19 04:20
Duplicate of #1114

**Closed by sreichel** 2023-01-19 04:20 UTC
Labels: bug confirmed, PR requested
