### ISSUE TITLE
catalog price rules: affected products touch "updated_at"

### ISSUE THREAD

**Issue by seansan** [OpenMage/magento-lts#341] opened 2017-09-11 18:31 UTC
catalog price rules: affected products touch "updated_at"

we have used catalog price rules for the first time this year
powerfull (if effective)
the problem we ran into is: that indexers dont seem to be triggered ... both situations when the first date where the catalog price rules should apply and where the catalog price rules were stopped were reached:we had to kick the system multiple times to notice and change it on the frontend

hence:
would it be an idea that 
- if a catalog price rule is in effect
- and the catalog price rule valid based on from-to dates

to change the product updated_at data or give the (product and product price) indexer a small push?

**Comment by fballiano** [comment] 2022-05-01 19:20
Sorry, I can't reproduce the problem, I think I'd need a more detailed use case. 

Since this issue didn't get any feedback since almost 5 years I'm closing it, but fell free to reopen if you feel so, with more info and a PR if possible, it would really help everybody :-)

**Closed by fballiano** 2022-05-01 19:20 UTC
