### ISSUE TITLE
separate connection to db write and read endpoints

### ISSUE THREAD

**Issue by alevashov** [OpenMage/magento-lts#1716] opened 2021-07-02 05:09 UTC
### Summary (*)
Seek guidelines/best practices to configure OpenMage working with separated read and write DB connections.

### Examples (*)

Specifically plan to use with AWS Aurora cluster that has 2 endpoints (writer and reader) and reader endpont connected with one or more replicas (managed by Aurora), but more generic separation where separate read and write endpoints defined probably will work too.

### Proposed solution
Will the config as below work? 
```

<default_setup>
                <connection>
                     <host><![CDATA[yourwriterhost.com]]></host>
                    <username><![CDATA[user]></username>
                    <password><![CDATApassword]]></password>
                    <dbname><![CDATA[dbname]]></dbname>
                    <initStatements><![CDATA[SET NAMES utf8]]></initStatements>
                    <model><![CDATA[mysql4]]></model>
                    <type><![CDATA[pdo_mysql]]></type>
                    <pdoType><![CDATA[]]></pdoType>
                    <active>1</active>
                </connection>
</default_setup>

<default_read>
                <connection>
                     <host><![CDATA[yourreaderhost.com]]></host>
                    <username><![CDATA[user]]></username>
                    <password><![CDATA[password]]></password>
                    <dbname><![CDATA[dbname]]></dbname>
                    <initStatements><![CDATA[SET NAMES utf8]]></initStatements>
                    <model><![CDATA[mysql4]]></model>
                    <type><![CDATA[pdo_mysql]]></type>
                    <pdoType><![CDATA[]]></pdoType>
                    <active>1</active>
                </connection>
</default_read>
```

**Comment by alevashov** [comment] 2021-07-16 04:39
Since no other answers here is a section of config file (local.xml) that worked in our case:
```
<resources>
    <db>
        <table_prefix><![CDATA[]]></table_prefix>
    </db>
    <default_setup>
        <connection>
            <host><![CDATA[WRITE_HOST]]></host>
            <username><![CDATA[WRITE_USER]]></username>
            <password><![CDATA[WRITE_PASS]]></password>
            <use/>
            <dbname><![CDATA[WRITE_DB]]></dbname>
            <initStatements><![CDATA[SET NAMES utf8]]></initStatements>
            <model><![CDATA[mysql4]]></model>
            <type><![CDATA[pdo_mysql]]></type>
            <pdoType><![CDATA[]]></pdoType>
            <active>1</active>
        </connection>
    </default_setup>
    <core_write>
        <connection>
            <use>default_setup</use>
        </connection>
    </core_write>
    <core_read>
        <connection>
            <use>default_read</use>
        </connection>
    </core_read>
    <default_read>
        <connection>
            <host><![CDATA[READ_HOST]]></host>
            <username><![CDATA[READ_USER]]></username>
            <password><![CDATA[READ_PASS]]></password>
            <use/>
            <dbname><![CDATA[READ_DB]]></dbname>
            <initStatements><![CDATA[SET NAMES utf8]]></initStatements>
            <model><![CDATA[mysql4]]></model>
            <type><![CDATA[pdo_mysql]]></type>
            <pdoType><![CDATA[]]></pdoType>
            <active>1</active>
        </connection>
    </default_read>
</resources>

```

We had to modify code of couple extensions that tried to bypass standard ways to access the DB.

**Comment by henryhayes** [comment] 2021-11-28 19:48
> Since no other answers here is a section of config file (local.xml) that worked in our case:
> 
> ```
> <resources>
>     <db>
>         <table_prefix><![CDATA[]]></table_prefix>
>     </db>
>     <default_setup>
>         <connection>
>             <host><![CDATA[WRITE_HOST]]></host>
>             <username><![CDATA[WRITE_USER]]></username>
>             <password><![CDATA[WRITE_PASS]]></password>
>             <use/>
>             <dbname><![CDATA[WRITE_DB]]></dbname>
>             <initStatements><![CDATA[SET NAMES utf8]]></initStatements>
>             <model><![CDATA[mysql4]]></model>
>             <type><![CDATA[pdo_mysql]]></type>
>             <pdoType><![CDATA[]]></pdoType>
>             <active>1</active>
>         </connection>
>     </default_setup>
>     <core_write>
>         <connection>
>             <use>default_setup</use>
>         </connection>
>     </core_write>
>     <core_read>
>         <connection>
>             <use>default_read</use>
>         </connection>
>     </core_read>
>     <default_read>
>         <connection>
>             <host><![CDATA[READ_HOST]]></host>
>             <username><![CDATA[READ_USER]]></username>
>             <password><![CDATA[READ_PASS]]></password>
>             <use/>
>             <dbname><![CDATA[READ_DB]]></dbname>
>             <initStatements><![CDATA[SET NAMES utf8]]></initStatements>
>             <model><![CDATA[mysql4]]></model>
>             <type><![CDATA[pdo_mysql]]></type>
>             <pdoType><![CDATA[]]></pdoType>
>             <active>1</active>
>         </connection>
>     </default_read>
> </resources>
> ```
> 
> We had to modify code of couple extensions that tried to bypass standard ways to access the DB.

I can confirm that this works for us

```
<resources>
    <db>
        <table_prefix><![CDATA[]]></table_prefix>
    </db>
    <default_setup>
        <connection>
            <host><![CDATA[master.host.com]]></host>
            <username><![CDATA[master_username]]></username>
            <password><![CDATA[master_password]]></password>
            <use/>
            <dbname><![CDATA[master_db]]></dbname>
            <initStatements><![CDATA[SET NAMES utf8]]></initStatements>
            <model><![CDATA[mysql4]]></model>
            <type><![CDATA[pdo_mysql]]></type>
            <pdoType><![CDATA[]]></pdoType>
            <active>1</active>
        </connection>
    </default_setup>
    <default_read>
        <connection>
            <host><![CDATA[slave.host.com]]></host>
            <username><![CDATA[slave_username]]></username>
            <password><![CDATA[slave_password]]></password>
            <use/>
            <dbname><![CDATA[slave_db]]></dbname>
            <initStatements><![CDATA[SET NAMES utf8]]></initStatements>
            <model><![CDATA[mysql4]]></model>
            <type><![CDATA[pdo_mysql]]></type>
            <pdoType><![CDATA[]]></pdoType>
            <active>1</active>
        </connection>
    </default_read>
    <core_write>
        <connection>
            <use>default_setup</use>
        </connection>
    </core_write>
    <core_read>
        <connection>
            <use>default_read</use>
        </connection>
    </core_read>
</resources>
```

We're using a master/slave DB system. Might also be a good idea to save your session info on the file system as opposed to in the DB because of the potential lag between master and slave.

**Comment by alevashov** [comment] 2021-11-28 23:32
We have our sessions in Redis, files are not good in our case since we have multiple web server nodes

**Comment by elidrissidev** [comment] 2022-09-28 09:16
Closing since it seems OP has resolved his issue.

**Closed by elidrissidev** 2022-09-28 09:16 UTC
Labels: needs investigation
