### ISSUE TITLE
Cleanup: Remove Mage_Adminhtml_Block_Notification_Survey

### ISSUE THREAD

**Issue by kkrieger85** [OpenMage/magento-lts#1095] opened 2020-07-06 13:51 UTC
This block and the corresponding template shows a message in Adminhtml which referres to magento survey

![2020-07-06_15-50](https://user-images.githubusercontent.com/4435523/86600606-8b3e2600-bfa0-11ea-9db5-cb7299c6abba.png)

**Comment by fballiano** [comment] 2020-07-09 10:19
couldn't this be considered duplicate of https://github.com/OpenMage/magento-lts/issues/683 ?

**Closed** 2022-05-02 13:50 UTC
