### ISSUE TITLE
The graphs in the Dashboard page no longer display data

### ISSUE THREAD

**Issue by ADDISON74** [OpenMage/magento-lts#4058] opened 2024-06-30 17:26 UTC
Latest OM version 20 cloned today from the repository. DDEV + PHP 8.3 + Apache + Maria DB + Magento Sample Data.

Steps to reproduce this issue:

1. Place an order in the Frontend
2. Go to the Backend and edit this order and ship it
3. Go to the Dashboard page and look to the charts in both tabs **Orders** and **Amounts**. For the current day it displays the word "chart" for other time range nothing is displayed.

![screenshot](https://github.com/OpenMage/magento-lts/assets/8360474/f985868c-aaed-40ee-bcaa-933e8f628766)

I went further completing the order issuing the Invoice. Nothing changed in the charts. At this moment in production an older version is displaying correctly the graph even I am only shipping the orders, not completing them (it is cash on delivery only). Both tabs display the graphs

![screenshot_2](https://github.com/OpenMage/magento-lts/assets/8360474/51c5ad42-03af-4683-8adf-5c5da47ed678)

I guess we should check the history for this file /app/code/core/Mage/Adminhtml/Block/Dashboard/Graph.php.

**Comment by maximus-sallam** [comment] 2024-07-01 06:08
Did you already perform typical troubleshooting like flushing the application cache and page cag , the Cloudflare cache (this takes 15 minutes), and the browser cache, cookies, site data, and history? Have you used a tool like curl to retrieve headers of the file that appears to fail to display the most recent change? Have you tested with Nessus, burpsuite, or Ghidra?

**Comment by ADDISON74** [comment] 2024-07-01 07:46
@maximus-sallam - I am an advanced OM user. In my case I use a DDEV test environment for which I created a tutorial in the Discussions section. 

I have enabled log files, debugging, the cache is disabled. My opinion that it is possible that there is a dropped or rejected connection to the source for the graphic.  

The file responsible for generating the chart is /app/code/core/Mage/Adminthml/Block/Dashboard/Graph.php. API_URL is https://image-charts.com/chart

I will check again these day.

**Comment by maximus-sallam** [comment] 2024-07-01 07:53
Are there any errors present in the PHP and Apacje Error logs, or Magento system.log, exception.log, and debug.log?

**Comment by ADDISON74** [comment] 2024-07-01 07:58
If there were errors I would have mentioned them, but there are not. I will check the connection with that URL.

**Comment by maximus-sallam** [comment] 2024-07-01 08:22
> > - [ ] I have an old store that has mandatory changes in the files located here /lib/Zend/Locale/Data/{en.xml, ...}, mainly for currency positions with different languages.

> - [ ] 
> - [ ] Meanwhile we removed Magento Zend from /app/.code/core and /lib, and OpenMage now requests using Composer to install ZF1-Future. If I change the files in this directory [`/vendor/shardj/zf1-future/library/Zend/Locale/Data`] they will be replaced with every update.
> - [ ] 
> - [ ] Do we have a loopback for changes related to the Zend folder? I tried to copy the modified files in both directories /app/code/core/Zend and /lib/Zend without any luck.





The vendor directory is reserved for composer modules and is managed through composer. You should not be editing the contents of vendor directory manually ever. app/code/ is the directory for custom/non-composer modules. The correct file hierarchy is app/code/vendor-name/module-name/files. Why did you put the core directory in the vendor-name location? Also, additional modifications, that facilitate management, have been made to modules installed in the vendor directory so you can't just copy and paste. You can download the app/code Zend files for your version of Magento from Magento's official Github page. 

Also, Zend Framework is now the Laminas Project. Did you check if it installed it automatically in place of Zend? Do you mean there's a customization that's been made to the application or one of the modules that's hardcoded to point to that vendor/zend file? Which one? Using hardcoded paths is a direct violation of guidelines set in the Magento coding standards for developers, in order to prevent the situation you're in now, shown here: 

https://github.com/magento/Magento-coding-standard https://developer.adobe.com/commerce/php/coding-standards/ https://developer.adobe.com/commerce/php/coding-standards/php/ https://developer.adobe.com/commerce/php/coding-standards/technical-guidelines/

Who made this change?

**Comment by maximus-sallam** [comment] 2024-07-01 08:29
> If there were errors I would have mentioned them, but there are not. I will check the connection with that URL.

Are you certain? I've managed thousands of Magento sites and they rarely have zero error messages logged? Are you certain you've checked all 5 different log files? Php_error.log, apache_error.log, debug.log, exception.log, and system.log all have zero entrie? The PHP error log, apache error log, and Magento error logs will be in 3 different locations and backed up, compressed, and cleared daily. Are they completely empty? Is logging enabled? Surely it is for PHP and Apache, but Magento logging needs to be enabled.

**Comment by maximus-sallam** [comment] 2024-07-01 08:34
Also, have you tried installing Zend via composer the correct way? 

$ composer require magento/module-zend

The package name might be wrong. Use composer list to display the available options, use the search option to search for zend, then it'll display the correct package name to use.

If this is Magento 1.x, it's going to be using an older version of Zend, so check the version set in the composer.json file.

**Comment by ADDISON74** [comment] 2024-07-01 08:38
@maximus-sallam - With all due respect, but we are in the OpenMage repository which continues Magento 1. I will delete your messages because they are off-topic.

**Comment by ADDISON74** [comment] 2024-07-01 08:41
@maximus-sallam - With all due respect, but we are in the OpenMage repository which continues Magento 1 platform. I deleted some of your messages because they are off-topic.

**Comment by maximus-sallam** [comment] 2024-07-01 08:47
> @maximus-sallam - With all due respect, but we are in the OpenMage repository which continues Magento 1. I deleted some of your messages because they are off-topic.

Ah, my apologies. I did confuse Magento 2 and 1 in my last comment, but  I don't think that warranted deleting all of my comments, many of which were valid in reference to Magneto 1.x or your issue.

> My opinion that it is possible that there is a dropped or rejected connection to the source for the graphic.

If that's the case, you can replay the GET request to the API using curl to display response codes. If that returns a 200 OK when sent from the server, than it's unlikely the API connection.

**Comment by ADDISON74** [comment] 2024-07-01 08:58
Cron was installed correctly on my DDEV environment. I will follow the curl tip. Thank you.

**Comment by maximus-sallam** [comment] 2024-07-01 09:09
You're welcome. You can use Burpsuite to record and replay the GET request, or you can review the curl PHP function that you found the API domain name in, in the Graph.php file, and use php -r from the command line to execute the code responsible for generating the GET REQUEST, and print it to the screen.

**Comment by fballiano** [comment] 2024-07-01 11:17
on the main branch I can't reproduce the problem:

<img width="1488" alt="Screenshot 2024-07-01 alle 12 17 19" src="https://github.com/OpenMage/magento-lts/assets/909743/6c9271c2-3256-4391-9b7e-ceb8a0975681">

**Closed** 2024-07-01 13:10 UTC
Labels: needs investigation
