### ISSUE TITLE
Session validation failure in Magento 1 EE v 1.14.3.x (and CE 1.9.3.x)

### ISSUE THREAD

**Issue by proxium** [OpenMage/magento-lts#394] opened 2017-11-29 15:07 UTC
Hi, we are seeing an increase amount of this exception:

    2017-11-22T08:30:27+00:00 ERR (3): 
    exception 'Mage_Core_Model_Session_Exception' in 
    /magento/src/app/code/core/Mage/Core/Model/Session/Abstract/Varien.php:421

I'm using Magento ver. 1.9.3.6 and Memcached also switched the session storage to Files, both session storage systems didn't avoid the exception.

There is a thread on StackOverflow that explains the exception and present a "workaround", you can check it here: https://magento.stackexchange.com/questions/167616/session-validation-failure-in-magento-1-ee-v-1-14-3-x-and-ce-1-9-3-x

Do you have an idea how to avoid rewriting the core files or how to avoid this error?

**Comment by colinmollenhour** [comment] 2017-11-29 20:07
I think this should be fixed by modifying core code and moving the validator data to it's own key and not duplicating it for every namespace which would also shrink the overall session storage considerably.

**Comment by sreichel** [comment] 2017-12-04 16:20
@colinmollenhour if you have time for, can you take a look at this? Have same issue since 1.9.3.x and no better solution as suggested in the linked SO question ...

**Comment by colinmollenhour** [comment] 2017-12-04 17:09
I just committed the better solution in b8c5f4c. Please give it some testing and review and I'll create a proper PR if it looks all good.

**Comment by seansan** [comment] 2017-12-23 11:41
HI, I am using I'm using Magento ver. 1.9.3.7 and Redis. Strangely enough we also see this error now. Was this introduced recenlty with other merges?  

I just cherrypicked this fix and testing

**Comment by seansan** [comment] 2017-12-23 12:04
Most errors are gone, new one introduced: 

Notice: Undefined index: http_x_forwarded_for  in           app/code/core/Mage/Core/Model/Session/Abstract/Varien.php on line 456

nginx does not set http_x_forwarded_for

**Comment by rvelhote** [comment] 2018-01-03 12:12
I'm getting the same PHP notice in `system.log` as @seansan which is weird because the key is indeed set in the `$sessionData`. Also using Nginx; don't know if it's related. I will continue investigating.

**Comment by colinmollenhour** [comment] 2018-01-03 15:27
This key should never not be set because it is initialized with an empty array and never unset:

```
        $parts = array(
            self::VALIDATOR_REMOTE_ADDR_KEY             => '',
            self::VALIDATOR_HTTP_VIA_KEY                => '',
            self::VALIDATOR_HTTP_X_FORVARDED_FOR_KEY    => '',
            self::VALIDATOR_HTTP_USER_AGENT_KEY         => ''
        );
```

Do you have 'web/session/use_http_x_forwarded_for' enabled? I can't think of many cases where you want this enabled since if you're using a load balancer or reverse proxy and it's IP changes then all your sessions are invalidated and if there are multiple and sessions are assigned randomly then you will get random invalidations.

Anyway, I agree with @seansan's tweak to put the value assignment inside the if statement and have updated my PR accordingly.

**Comment by rvelhote** [comment] 2018-01-04 14:10
The `web/session/use_http_x_forwarded_for` option is disabled. For now we are still running on our development server which is made up of docker containers so there are no load balancers involved.

With the original Magento 1.9.3.7 file everything works well but as soon as I replace it with the file that contains this patch the sessions stop working. I will investigate further and will report back.

**Comment by jasuten** [comment] 2018-02-26 05:10
I can confirm the issue that @rvelhote mentioned with our install of Magento 1.9.3.7. I tracked the issue down to line 477 needing to be changed from:
            `$this->_data[self::VALIDATOR_KEY][self::VALIDATOR_SESSION_EXPIRE_TIMESTAMP]`
to:
            `$_SESSION[self::VALIDATOR_KEY][self::VALIDATOR_SESSION_EXPIRE_TIMESTAMP]`
Otherwise it causes issues on line 419 where it sets the session validator data to an array with only the session_expire_timestamp set, this then gives undefined index errors.

**Comment by colinmollenhour** [comment] 2018-02-27 16:27
Ahh, nice work @jasuten! This 'session_expire_timestamp' key did not exist when I first created this modification and when I ported it over to Magento LTS I failed to update the new code. I just pushed a new Pull Request to fix it. See #457

**Comment by colinmollenhour** [comment] 2018-03-09 19:35
Fixed!

**Closed by colinmollenhour** 2018-03-09 19:35 UTC
