### ISSUE TITLE
Can't get products by store view from catalogProductList API

### ISSUE THREAD

**Issue by luigifab** [OpenMage/magento-lts#1576] opened 2021-04-29 13:43 UTC
When we try to retrieve products from [catalogProductList API](https://r-martins.github.io/m1docs/guides/m1x/api/soap/catalog/catalogProduct/catalog_product.list.html), results is not filtered/displayed with the specified store id (here 19).

```php
$proxy = new SoapClient('https://.../api/v2_soap/?wsdl', ['user_agent' => 'Local/Test']);
$sessionId = $proxy->login('...', '...');
$products = $proxy->catalogProductList($sessionId, [], 19);
foreach ($products as $product)
	echo $product->product_id,' ',$product->name,"\n";
```

By adding _setStoreId_ in _Mage_Catalog_Model_Product_Api::items_, the problem is fixed.

```php
    public function items($filters = null, $store = null)
    {
        $storeId = $this->_getStoreId($store)
        $collection = Mage::getModel('catalog/product')->getCollection()
            ->setStoreId($storeId)
            ->addStoreFilter($storeId)
            ->addAttributeToSelect('name');
```

Not sure why. Not sure if it's only our OpenMage installation or not.
OpenMage 20.0.10 / PHP 7.4.6

**Comment by lamskoy** [comment] 2021-04-29 20:25
It can be related to difference in implementation of product collection when Flat Catalog is used and when it's turned off.

**Comment by lamskoy** [comment] 2021-04-29 20:31
https://github.com/OpenMage/magento-lts/blob/5a0b657f13c5aced93f50f67ba1905e6e4f39b97/app/code/core/Mage/Catalog/Model/Resource/Product/Collection.php#L661

It's calling **setStoreId()** method inside **addStoreFilter()**
Can you show **var_dump(get_class(Mage::getModel('catalog/product')->getCollection()))** output inside **Mage_Catalog_Model_Product_Api::items**

**Comment by luigifab** [comment] 2021-05-05 15:12
Here is the `get_class` in `Mage_Catalog_Model_Product_Api::items`:
```
2021-05-05T15:11:10+00:00 DEBUG (7): Mage_Catalog_Model_Resource_Product_Collection
```

**Comment by kiatng** [comment] 2021-05-06 01:29
I cannot replicate this issue with ver 20.0.7.

**Comment by luigifab** [comment] 2021-05-06 10:33
😢 I will search again.

**Comment by kiatng** [comment] 2021-05-07 02:21
See PR #1601, it has the same problem of not getting products by store, but probably not related to this issue.

**Comment by luigifab** [comment] 2021-05-18 15:31
I tried again with a fresh _app_ and _lib_ files of 20.0.10 (+ PR 1601 and 1603), with PHP 8.0.5, same result for me, I need to add the setStoreId to get the correct name.

**Comment by fballiano** [comment] 2022-05-02 18:25
@luigifab would it be possible for you to try it again on a v19 branch since now 1601 has been merged?

**Comment by elidrissidev** [comment] 2022-06-21 09:55
There seems to be some confusion here. `catalogProductList` is the method suffering from this bug, whereas `catalogProductInfo` works fine.

Here's a snippet that reproduces this issue assuming the product name in this case is different between admin and the other store:

```php
$client = new SoapClient('http://magentohost/index.php/api/v2_soap/?wsdl');
$session = $client->login('username', 'password');

// Product listing
$product = $client->catalogProductList($session, [
    'complex_filter' => [
        [
            'key' => 'entity_id', 
            'value' => ['key' => 'in', 'value' => '5573']
        ]
    ]
], 2);
echo 'Product listing: ' . $product[0]->name . PHP_EOL; // Shows name from default store

// Product info
$product = $client->catalogProductInfo($session, 5573, 2);
echo 'Product info: ' . $product->name . PHP_EOL; // Shows name from store with id 2
```

Replace product ID and store ID with yours.

**Closed** 2022-07-07 12:43 UTC
Labels: bug confirmed
