### ISSUE TITLE
M1931 - dropdown product atttribute sorting - is this possible that its broken?

### ISSUE THREAD

**Issue by tomekjordan** [OpenMage/magento-lts#170] opened 2017-02-10 10:42 UTC
Hi. I see strange sorting for dropdown product attributes in admin and frontend (I use this attribute for Catalog Sorting). I need to confirm but in M1924 it worked, and now on M1931 there is something broken with it.
[http://prntscr.com/e6wiib](url) Itoris, extension develope said its something wrong in the core
Frontend catalog sorting also shows incorrect things for this dropdown attribute
Attribute setting:
[http://prntscr.com/e6wizj](url)
[http://prntscr.com/e6wjb7](url)

Will check it deeply and let you know once 100% confirmed

Tomek

**Comment by colinmollenhour** [comment] 2017-02-10 17:18
I would suggest looking at the MySQL general log and comparing between versions to see if the MySQL query changed or not. If it did not then the problem is either in indexing or PHP. If it did then the fix will probably be pretty easy.

**Comment by robbieaverill** [comment] 2017-02-12 20:56
This is quite possibly the issue [that this module attempts to resolve](https://github.com/robbieaverill/magento-attribute-option-order-fix). Magento [bug report here](https://www.magentocommerce.com/bug-tracking/issue/index/id/413).

**Comment by tomekjordan** [comment] 2017-02-13 18:46
I don't think dropdown in product attributes is related to configurable products. Especialle I have 0 configurable products in my store....

**Comment by tomekjordan** [comment] 2017-02-13 19:26
UPDATE: just get some info from Itoris devs.

> After further investigation we confirmed it is a bug of Magento filters. They do not build the SQL query for the collection correctly when a multiselect attribute is filtered on the grid.
> 
> We managed to update the SQL query through our code. Please find file Grid.php attached. Put it in \app\code\local\Itoris\ProductGrid\Block\Admin\Catalog\Product\Grid.php. Let me know if it fixed on your end now.
> 
> Regarding the issue with sorting. It is also a Magento bug. The issue is each attribute value has ID in the database. Magento sorts by this ID instead of than value position. Unfortunately, adding sorting by position in this query will make the SQL running slowly. The issue looks like a limitation of Magento's EAV structure.

Is there any option to fix it right in the core?

Thanks

**Comment by seansan** [comment] 2018-09-05 12:45
Possible fix here? https://gist.github.com/Jonathonbyrd/407d57b2a458bbbd7f92#file-collection-php-L300

I do recall we implemented a similar fix. Or this was fixed in a later version

@tomekjordan can you confirm this is still an issue?

Related?
https://stackoverflow.com/questions/37941808/php-7-usort-adds-equal-items-to-end-of-array-where-in-php-5-it-adds-to-the-begin

**Comment by ADDISON74** [comment] 2022-05-15 09:34
This problem reported for 1.9.3.1 is almost 4 years old. Is still related in OpenMage?

**Closed** 2022-05-15 15:22 UTC
