### ISSUE TITLE
minicart error

### ISSUE THREAD

**Issue by Danieleeffe1** [OpenMage/magento-lts#1897] opened 2021-12-13 17:22 UTC
Hi everyone

I have a problem that occurs randomly

if I delete a product present in the openmage minicart it crashes

here is the crash log:

```
a:5:{i:0;s:16:"Invalid form key";i:1;s:909:"#0 /var/www/openmage/app/code/core/Mage/Checkout/controllers/CartController.php(641): Mage::throwException()
#1 /var/www/openmage/app/code/core/Mage/Core/Controller/Varien/Action.php(437): Mage_Checkout_CartController->ajaxDeleteAction()
#2 /var/www/openmage/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(262): Mage_Core_Controller_Varien_Action->dispatch()
#3 /var/www/openmage/app/code/community/ArtsOnIT/OfflineMaintenance/Controller/Router/Standard.php(46): Mage_Core_Controller_Varien_Router_Standard->match()
#4 /var/www/openmage/app/code/core/Mage/Core/Controller/Varien/Front.php(192): ArtsOnIT_OfflineMaintenance_Controller_Router_Standard->match()
#5 /var/www/openmage/app/code/core/Mage/Core/Model/App.php(381): Mage_Core_Controller_Varien_Front->dispatch()
#6 /var/www/openmage/app/Mage.php(752): Mage_Core_Model_App->run()
#7 /var/www/openmage/index.php(88): Mage::run()
#8 {main}";s:3:"url";s:160:"/checkout/cart/ajaxDelete/id/387/uenc/aHR0cHM6Ly9vcGVubWFnZS52ZXRyaW5hZGlnaXRhbGUuZXUvYWRlc2l2by1zY29udGktMWEtc2VtaXRyYXNwYXJlbnRlLmh0bWw_X19fU0lEPVU,/?___SID=S";s:11:"script_name";s:10:"/index.php";s:4:"skin";s:7:"default";}
```
php 7.4
mysql 8
apache 2.4
redis

**Comment by ADDISON74** [comment] 2021-12-13 18:48
I tried to reproduce this issue but without success. I tested all the side blocks of the shopping cart with an OpenMage 20.0.13 + Magento Sample Pack 1.9.0.1 version (RWD theme).

From what I see you're using an extension that might cause you trouble named **ArtsOnIT_OfflineMaintenance**. I would disable this extension and test again.

PS - lways try to check in a strict test environment with OpenMage without any custom modification or extension. Only then we can say that there is an issue in the code that requires special investigation.

**Comment by Danieleeffe1** [comment] 2021-12-14 06:56
so

the problem shows up with the FPC enabled.

is there a setup that needs to be done?

**Comment by ADDISON74** [comment] 2021-12-14 09:02
In the past I approached the Lesti_FPC extension and it was well maintained for a while but important problems arose and no solutions were found. Then I switched to Varnish + Turpentine for a couple of years. Now I don't use any FPC's anymore, I don't think it's important when you get a dedicated server with NVMe storage, enough RAM and lots of cores.

You need to look for the solution on the Git page of the extension or through forums. Most likely you need to add those blocks to no longer be cached.

**Comment by elidrissidev** [comment] 2021-12-22 09:34
Judging by the error message, I think what's happening here is the formkey input is being cached by the FPC extension, but I'm not so sure about that. You may want to try to convert the mini cart to be a dynamic block so that the formkey is set properly on the request: https://gordonlesti.com/what-are-lazy-and-dynamic-blocks-in-lesti-fpc/

**Comment by Danieleeffe1** [comment] 2022-01-07 13:38
After extensive research and endless tests, I solved my problem.

Basically Lesti_FPC is certainly very powerful, unfortunately to use it at 100% you need to be able to identify all the parameters based on your installation.

In my case I had to check and disable the functions added by the plug-ins (usually jquery) which had no reason to be active.

Also: I had installed a plug-in that moved the compressed Javascript files in the footer creating problems for Lesti_FPC and consequently generating the error in the cart.

I also had to add a couple of parameters in the Lesti_FPC fields to avoid storing errors in the mini cart when deleting a product.

Here is my configuration:

Actions cacheable

cms_index_index,
cms_page_view,
catalog_product_view,
catalog_category_view

Dynamic blocks

header_minicart,
global_messages,
messages,
global_notices,
global_cookie_notice,
right.reports.product.viewed

Update actions

checkout_cart_add,
checkout_cart_delete,
checkout_cart_updatePost,
checkout_cart_ajaxDelete,
checkout_cart_ajaxUpdate,
checkout_cart_updateItemOptions,
catalog_product_compare_add,
catalog_product_compare_clear,
catalog_product_compare_remove,
wishlist_index_add,
minicart_head,
mini_cartpro_content,
wishlist_index_remove,
wishlist_index_update,
wishlist_index_allcart,
wishlist_index_configure,
checkout_onepage_success,
customer_account_login,
poll_vote_add

Lazy blocks

top.link,
catalog.compare.sidebar,
right.report.the.product.to.comparison,
wishlist_sidebar,
Welcome,
law, survey,
header_minicart,
minicart_head

**Comment by elidrissidev** [comment] 2022-02-19 10:30
@Danieleeffe1 If you've solved your problem, can you close this issue?

**Comment by Danieleeffe1** [comment] 2022-02-19 10:38
No, I have no idea what caused the anomaly.

I have duplicated the products causing the problem and deleted the original products.

this is how it works

**Comment by elidrissidev** [comment] 2022-02-19 14:05
Did making the minicart block dynamic (i.e. not being cached) not solve the issue? We had similar issues in the past across many blocks, although with a different pagecache extension (Extendware) and that solved our issues.

**Comment by fballiano** [comment] 2022-05-01 20:39
This kind of issue is always showing when using a full page cache extension, this issue is a good documentation but it has no need to stay open since it's not OpenMage's fault.

**Closed by fballiano** 2022-05-01 20:39 UTC
