### ISSUE TITLE
PHP Error

### ISSUE THREAD

**Issue by guilhermeaquere** [OpenMage/magento-lts#1312] opened 2020-11-18 14:12 UTC
Hi guys! I recently upgraded to openmage and got this php error

http://i.imgur.com/PzF6EGR.png

**Comment by ADDISON74** [comment] 2020-11-18 14:33
Your report is far from being considered a good starting point in analyzing the cause. 

I am absolutely sure that this problem is not caused by OpenMage but by the way the upgrade was done. If it worked on the same server before, it should work after. OpenMage only embedded parts of code that were unresolved by the Magento team, with no changes to make serious changes. 

Are you sure you upgraded correctly to OpenMage? Please provide your steps.

Did you make any investigations? Have you tried disabling certain modules like that Amasty FPC to see if it works? I encountered that error when I mistyped an XML file.

**Comment by guilhermeaquere** [comment] 2020-11-18 14:57
Thanks for the reply and Sorry for the scope in which you brought the errors, I am a little layman in this matter.

My steps were to get the zip here on the openmage github and update my site via ftp.

How can I disable the amasty extension?

**Comment by ADDISON74** [comment] 2020-11-18 15:41
As I understand it was just an overwrite of the existing files. Personally I don't like this method and I prefer a clean up version when switching for Magento to OpenMage. 

First you should do a backup of your Magento file system and create a dump file of the database. Then take these two in a development server with the same configuration as the one used in production. 

Import all data into the database, the current user should have the right permissions, the same password to access the database like the one used in file /app/etc/local.xml. From mysql prompt do not forget to change the URL's for secure and unsecure in core_config_data table. 

Use WinSCP (Windows) which can allow a secured connection to the server and not ftp protocol. Open WinSCP for half of the screen and Windows Explorer for the other side with OpenMage LTS extracted. Investigate in your Magento window all folders one by one and compare with OpenMage in the other window. You should delete all unchanged files related to Magento default in root directory and in the other folders. In time you will become an expert what to keep or not if you repeat this step a few times. Let me give you a tip I keep files in the following directories:

- /app/code/community
- /app/code/local
- /app/design/frontend/base (check those installed by 3rd party by comparing with OpenLTS)
- /app/design/frontend/default/[your-theme]
- /app/etc
- /app/locale (for translations)
- /include/config.php (only if it was modified in case you operate behind a proxy server)
- /js (check those installed by 3rd party by comparing with OpenLTS)
- /media/catalog/
- /skin/adminhtml (compare if some 3rd party added some stuff here)
- /skin/frontend/base (compare if some 3rd party added some stuff here)
- /skin/frontend/default/[your-theme]

*) If you did change into the code you can make a diff between a Magento default folder and yours to identify the changes.

Now it is time to copy all files from OpenMage to the cleaned up file system. Open your browser and load the frontend and the backend. If you did correctly the steps the page will load without any issue. Activate logs in backend (system, exceptions), logs on webserver, PHP and check them periodically. 

Any module can be disabled by editing its configuration file located in /app/etc/module and set active from true to false. Delete the cache (/var/cache) and reload the page.

What I wrote here is pretty basic but  there are tons of documentation on Internet. When you ask "how to disable a module" it is clear you have to improve your knowledge about Magento asap.

**Comment by kiatng** [comment] 2020-11-19 02:23
I am not sure about Amasty extensions, but you can disable them by removing its files from this directory: `app\etc\modules`. If OM starts, you can put back the files you removed one at a time to identify which extension caused the error.

**Comment by guilhermeaquere** [comment] 2020-11-19 16:41
I disabled the amasty extension and it is working normally, thanks for the replies!

Even so, I would like to take some questions with you if possible:

Isn't Amasty's extension a differentiator for website performance and loading?

I noticed that my site is a little slower after updating and disabling the extension

**Comment by kiatng** [comment] 2020-11-20 03:19
My client doesn't use any Magento extension for performance. The big performance boost I experienced was when we upgraded to PHP 7 with the latest OM at the time. If you are not on PHP 7, you should. But it may not be compatible with 3rd-party extensions.

**Comment by Flyingmana** [comment] 2020-11-20 08:15
@guilhermeaquere you are right, the Amasty extension is providing an improvement for the website performance and loading, and now as we know, the problem is inside the extension, we can see how to solve this.
And as this was working before, and now is not with OpenMage, this is a bug we need to find a solution for.

I see 2 Possibilities currently.
1. there is a known problem with this module, so you could try to see if this comment is helping: https://github.com/OpenMage/magento-lts/issues/990#issuecomment-725192261

2. because of the error message (it would be good, if you can copy&paste them in here, not only as a screenshot, helps with beeing searchable in the future) I think there could have been an upload error. could you re-upload all the Files of this specific module, maybe something did go wrong in one of the xml files or similar.

**Comment by fballiano** [comment] 2021-04-06 20:46
I suggest we close this issue since it doesn't have feedback since 4 months and it was related to a 3rd party extension which was probably uninstalled by OP.

**Closed** 2021-04-08 07:51 UTC
